### ISSUE TITLE
Legend is missed for argument x = -1

### ISSUE THREAD

**Issue by k-viktor-p** [danvk/dygraphs#1002]
https://jsfiddle.net/0h1z72s0/

Legend is missed for argument x = -1, and to legend formatter passed value 'underfined'

**Comment by danvk** [comment]
@k-viktor-p do you need to update the link? That's just the default dygraph jsfiddle.

**Comment by kevingross** [comment]
https://jsfiddle.net/3t1Lxp2j/

I have the same problem of missing legend when argument x = -1. I updated the jsfiddle to show the issue.

After looking in the source code, there is a test done which send 'undefined' when x = -1, see the extraction below:
`this.cascadeEvents_('select',{selectedRow:this.lastRow_ === -1?undefined:this.lastRow_,selectedX:this.lastx_ === -1?undefined:this.lastx_,selectedPoints:this.selPoints_});`

**Comment by mirabilos** [comment]
fixed in git
