### ISSUE TITLE
The main menu on the site does not work

### ISSUE THREAD

**Issue by Curiouslynx** [danvk/dygraphs#1008]
Try using the main menu on the page https://dygraphs.com/tutorial.html

console:

Mixed Content: The page at 'https://dygraphs.com/tutorial.html' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.
bootstrap.min.js:6 Uncaught ReferenceError: jQuery is not defined
    at bootstrap.min.js:6

**Comment by mirabilos** [comment]
CDNs are a bad idea anyway, also for EU-GDPR compliance.

**Comment by mirabilos** [comment]
fixed
