### ISSUE TITLE
drawAxis have no clue

### ISSUE THREAD

**Issue by vlxhzb** [danvk/dygraphs#1017]
I ask for the solvation of my problem to always show y2 axis.

_Here is the article at stackoverflow without a result._

https://stackoverflow.com/questions/71143168/dygraph-y2-axis-was-never-shown

If I need different data series filled with data sets to show the right axis, then `drawAxis` is obsolete at the moment. But this shrink the functionality of dygraph to generate the same view to more than one dygraph in a site. 

Next issue is related to the actual situation. If the y2 axis isn't shown, the dygraph automatically fill the space and disrespect the formerly set width of the canvas. The space of the second axis is not subtracted from the single axis dygraph.

These two problems in once steel me two weeks. Please fix it.

**Comment by mirabilos** [comment]
I commented at the StackOverflow question: the jsfiddle you gave shows both Y axēs rendered, so this is not reproducible.
