### ISSUE TITLE
plot not correctly displayed in right to left writing environment

### ISSUE THREAD

**Issue by mehdihadi** [danvk/dygraphs#1019]
Hi,
Thanks for any help to solve the following issue I asked in my stakeoverfolw. 

https://stackoverflow.com/questions/71998804/r-dygraph-plot-not-correctly-displayed-in-right-to-left-shiny-app

Thanks again
Mahdi

**Comment by mirabilos** [comment]
can you provide a small test case (like the HTML files under `tests/`; in fact, copy `tests/demo.html` or so and modify it) that exhibits the problem?

**Comment by mirabilos** [comment]
@mehdihadi I’ve tried to do that myself and found the biggest showstopper.

Have a look at https://dygraphs.com/tests/rtl.html (might need to press Ctrl-Shift-R to get the latest css and js if your browser still has it cached). Anything more will need community input from a native speaker of an RTL language, I fear…
