### ISSUE TITLE
Unable to set the axisLabelColor in dygraph v2.1.0

### ISSUE THREAD

**Issue by saivikas-ethakota** [danvk/dygraphs#1021]
Hi 

I am using dygraphs version 2.1.0 with the angular 12 application. I need to change the axis label color to a specific color. 

I have tried using the **axisLabelColor** option but it doesn't work.

Is there a way to change the axis label color of the graph ??

Below is a sample code that I have tried

``var g = new DyGraphs(
      this.ecgTwoGraphElement.nativeElement,
      r, {
      width: 600,
      height: 300,
      labels: ["Date", "a", "b"],
      axisLabelWidth: 15,
      axisLabelFontSize: 10,
      axisLabelColor: "white",
      axisLineColor: "white",
      axisLineWidth: 1.5,
      gridLineColor: 'grey',
      gridLineWidth: 1.0,
      strokeWidth: 2.0,
      xRangePad: 5.0,
      axes: {
        x: {
          drawGrid: false,
          drawAxis: true
        },
        y: {
          drawGrid: true,
          drawAxis: true
        }
      }
    }
    );
  }`
`

**Comment by mirabilos** [comment]
This was replaced with CSS in dygraphs 2:

```
.dygraph-axis-label {
  color: black;  /* replaces old axisLabelColor option */
}
```
