### ISSUE TITLE
missing licence for some tests with ©/ARR remark

### ISSUE THREAD

**Issue by mirabilos** [danvk/dygraphs#1024]
The following files have an **explicit** copyright statement but no licence:

- auto_tests/tests/PixelSampler.js
- auto_tests/tests/css.js
- auto_tests/tests/custom_bars.js
- auto_tests/tests/range_selector.js
- auto_tests/tests/selection.js
- auto_tests/tests/update_options.js

This normally means they are unredistributable even.

For the other tests without an explicit licence statement, they also do not have a copyright statement of their own, and so the project-wide MIT licence applies.

Best fix would be adding the MIT licence to these files as well iff their copyright holder agrees (that’s `Google, Inc.` for all of these) or even better removal of these explicit copyright statements, given Google’s listed elsewhere already and these are just tests, but that definitely needs permission from them.

**Comment by mirabilos** [comment]
@danvk @paulfelix @clocksmith could you please look at these files and clarify their licence?

**Comment by danvk** [comment]
Hi @mirabilos -- thanks for the PRs and issues. As you may have noticed (#727) dygraphs hasn't seen much active development recently. If you'd be interested in becoming an owner, please let me know!

**Comment by mirabilos** [comment]
Dan Vanderkam @danvk dixit:

>Hi @mirabilos -- thanks for the PRs and issues. As you may have noticed
>(#727) dygraphs hasn't seen much active development recently.

Yes, I’ve seen that. I’m trying to package what’s there for Debian.
For basically any use, though, we (as in the world) needs this licence
issue clarified. Otherwise, the test files in question will need to
be deleted…

>If you'd be interested in becoming an owner, please let me know!

Unsure about that yet. I’m not an ECMAscript developer. I’ll have to
work with this a bit more to be able to see about that in the first
place.

bye,
//mirabilos
-- 
I believe no one can invent an algorithm. One just happens to hit upon it
when God enlightens him. Or only God invents algorithms, we merely copy them.
If you don't believe in God, just consider God as Nature if you won't deny
existence.		-- Coywolf Qi Hunt

**Comment by paulfelix** [comment]
The files are all test files. Can someone just add the MIT license to them? That's certainly my wish for any file I authored.

**Comment by mirabilos** [comment]
Paul Felix dixit:

>The files are all test files. Can someone just add the MIT license to
>them? That's certainly my wish for any file I authored.

Sure, can do (in my fork, in which I also prepare the Debian packaging),
but we need positive agreement to do so from all three people involved…
actually also from Google, Inc. since it bears their name as copyright
holder.

bye,
//mirabilos
-- 
I believe no one can invent an algorithm. One just happens to hit upon it
when God enlightens him. Or only God invents algorithms, we merely copy them.
If you don't believe in God, just consider God as Nature if you won't deny
existence.		-- Coywolf Qi Hunt

**Comment by danvk** [comment]
@mirabilos I added an explicit MIT license to each of the test files you mentioned. Hopefully this resolves the issue.

**Comment by mirabilos** [comment]
Hi Dan,

***@***.*** I added an explicit MIT license to each of the test files
***@***.*** mentioned. Hopefully this resolves the issue.

if you’re in the legal position to do so, then, yes.

Thank you!

bye,
//mirabilos
-- 
I believe no one can invent an algorithm. One just happens to hit upon it
when God enlightens him. Or only God invents algorithms, we merely copy them.
If you don't believe in God, just consider God as Nature if you won't deny
existence.		-- Coywolf Qi Hunt
