### ISSUE TITLE
bug in dygraph.min.js

### ISSUE THREAD

**Issue by AdrieK** [danvk/dygraphs#1027]
I get an error using the online version of
<script src="//cdnjs.cloudflare.com/ajax/libs/dygraph/2.1.0/dygraph.min.js"></script> in a webpage

The error at including the file is: 
"DevTools failed to load source map: Could not load content for https://cdnjs.cloudflare.com/ajax/libs/dygraph/2.1.0/dist/dygraph.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE"

If I understand the problem dygraph.min.js.map is not in the /2.1.0/dist directory but in the /2.1.0/ 

The last line of dygraph.min.js refers to 
#sourceMappingURL=dist/dygraph.min.js.map 
Should be without the dist/ if I'm correct.
(the not .min(imal) version doesn't has the issue)

**Comment by mirabilos** [comment]
I haven’t found out how to publish to cdnjs yet, but unpkg took over the updated npm package immediately, so you can try:

    https://unpkg.com/dygraphs@2.1.2-alpha.1/dist/dygraph.min.js

I expect there to be a mostly unchanged, but merged back to this repo, 2.1.2 release soon.

**Comment by mirabilos** [comment]
Fixed in v2.1.2
