### ISSUE TITLE
Hide the scale lable value

### ISSUE THREAD

**Issue by wanghe199512** [danvk/dygraphs#1031]
![1679467739344](https://user-images.githubusercontent.com/38382084/226824032-da1e35a3-57b6-4356-b267-bf5a214a31b8.png)
Can you hide the value of the y,x scale, and the zero line is fixed in the middle？thanks

**Comment by mirabilos** [comment]
You can set the appropriate `axisLabelFormatter` to return empty strings and set `valueRange` symmetrically (`[-ymax, ymax]`) so the 0 is always in the middle
