### ISSUE TITLE
 How to use the click event in the synchronous example to get the corresponding information of all graphs

### ISSUE THREAD

**Issue by wanghe199512** [danvk/dygraphs#1032]
![1679539034925](https://user-images.githubusercontent.com/38382084/227085871-34af8d87-26d1-4419-b133-a69aa3c31e85.png)

I'm trying to draw a line graph. When I use the clickCallback and clickPointCallback methods, unfortunately it can only get the data on one graph. I want to get the position and data of the corresponding points of the four graphs. Is there any way? I'm a novice ,Thanks

**Comment by mirabilos** [comment]
Look at the synchroniser extra plugin, for example it is used in https://dygraphs.com/tests/synchronize.html (but you’ll have to look at the source code (for both the use case and the plugin itself) to see how it works).

Unfortunately, I cannot do “hand-holding” of novices, I don’t have the resources for that (and I’m somewhat new to JS libs as well). You could try the [mailing list](https://groups.google.com/g/dygraphs-users) but I’m afraid it’s very much not active either, or asking on StackOverflow, for individual support. It’s best to keep the bugtracker for actual bugs…
