### ISSUE TITLE
about xValueParser Crosshair Offset bug

### ISSUE THREAD

**Issue by wanghe199512** [danvk/dygraphs#1033]
I've been learning how to draw charts using frames recently, and when using xValueParser in the current version, the crosshairs are shifted

![image](https://user-images.githubusercontent.com/38382084/227490407-b93c108f-6a00-4b7b-8404-20fc05c1d26b.png)

The resulting exception code is as follows:

xValueParser: function(res) {
	return res
}；

Remove the xValueParser and the display will be normal

I checked the source code, the default is to format the date format, but in some occasions it may not need to be formatted, and it returns directly

**Comment by mirabilos** [comment]
when you have an MWE, get back to us; until then, this seems to work as expected
