### ISSUE TITLE
how to move highlight point on mouse move event in Dygraph

### ISSUE THREAD

**Issue by SecretariatV** [danvk/dygraphs#1042]
Here are two Dygraphs.
I am going to move highlight point and legend of first Dypgraph when mouse moves on second one.
How can I solve this?

**Comment by mirabilos** [comment]
It’s better to ask user questions on the [mailing list](https://groups.google.com/g/dygraphs-users); this is a bugtracker.

As to your question, the [synchroniser plugin](https://dygraphs.com/gallery/#g/synchronize) does what you want, if I understand you correctly.
