### ISSUE TITLE
RangeSelector slowing things down quite badly

### ISSUE THREAD

**Issue by danvk** [danvk/dygraphs#399]
_From [fkn...@gmail.com](https://code.google.com/u/114223773186722146498/) on April 30, 2013 20:46:43_

Hi there,

I'm using this wonderful library for plotting a fairly large amount of data (100,000 data points).

Dygraphs itself handles it very well, and it's all pretty fast and snappy --- until I enable the RangeSelector, which pretty much gets things grinding to a halt.

I know this is a very broad complaint -- you're welcome to say: well, then, fix it! -- but there seems to be a large discrepancy in terms of performance. Is this a know issue?

Thanks and best wishes,

Florian

_Original issue: http://code.google.com/p/dygraphs/issues/detail?id=468_

**Comment by panuhorsmalahti** [comment]
Fix was merged in:
https://github.com/danvk/dygraphs/pull/448
