### ISSUE TITLE
X Axis is always in local time

### ISSUE THREAD

**Issue by danvk** [danvk/dygraphs#416]
_From [russnel...@gmail.com](https://code.google.com/u/102355438470080501971/) on December 05, 2013 15:05:33_

The X Axis is always generated using local time, even if the data is UTC. You can see this by zooming any dygraphs implementation to November 3rd, 2013 if your browser's time zone is set to a DST-respecting time zone.

This is a problem because we're trying to give the finger to daylight savings for our published data, by using UTC everywhere. The USGS does something similar by always using local time without DST.

I wish there was a i-hate-you-daylight-savings-time-die-die-die option, to banish DST from the X Axis and datetime parsing.

But I suppose a reasonable default would be to use a UTC X axis if dates are presented an ISO8601 format using Z. https://en.wikipedia.org/wiki/ISO_8601

_Original issue: http://code.google.com/p/dygraphs/issues/detail?id=498_

**Comment by squaregoldfish** [comment]
I believe this was fixed in the 1.1.0 release. (labelsUTC option)
