### ISSUE TITLE
setVisibility() can cause the last data series to vanish from setIndexByName_

### ISSUE THREAD

**Issue by danvk** [danvk/dygraphs#434]
_From [sergeysl...@gmail.com](https://code.google.com/u/108873442384158821856/) on July 09, 2014 17:45:30_

Here's a JSFiddle reproducing the problem: http://jsfiddle.net/X68vR/2/ Here's how to reproduce this error in the JSFiddle:

1) Use the checkbox to hide the last time series (Random2).

2) Wait one second for the graph to update.

3) Attempt to show the last time series using the checkbox.

Expected:

Time series should be shown again.

Actual:

Time series is not shown again, because indexFromSetName() can't find the series anymore, because it's gone from setIndexByName_

This bug does not happen on any time series except the very last one.

This bug also doesn't happen if you don't use indexFromSetName(), and just reference the series id directly.

_Original issue: http://code.google.com/p/dygraphs/issues/detail?id=518_

**Comment by sslepian** [comment]
As a note, getPropertiesForSeries() can also be used to get the series index (it's the column property) and does not suffer from this issue.

**Comment by danvk** [comment]
Fixed by #771
