### ISSUE TITLE
Please add text from old website

### ISSUE THREAD

**Issue by timmie** [danvk/dygraphs#452]
Hello,
would it be possible to add the following text from the old website (maybe also to the documentation?

http://dygraphs.com/old-site/
Text:

A demo is worth a thousand words:

(Mouse over to highlight individual values. Click and drag to zoom. Double-click to zoom back out. Change the number and hit enter to adjust the averaging period.)

Daily Temperatures in New York vs. San Francisco
[GRAPHICS]
 
Some things to notice:
•There's less seasonal temperature variation in SF than in NY.
•The difference is about 15° F for SF vs. 50° F for NY.
•The daily data (set rolling period to 1) is quite noisy and hides this conclusion.
•Using a 14-day moving average makes it clearer. A 100-day rolling period averages out nearly all the specifics from the data.
•There's a gap in the data for SF, when the weather station was down (zoom into October 2007 to see it).
•The bands around each point indicate average highs and lows.
•There is a lot of data in this chart: low, average and high for each city on each day of a three year period ≈ 6000 data points in all.

dygraphs allows the user to explore the data and discover these facts.

**Comment by kbaggott** [comment]
I'm not saying this isn't a valid request, but with no reply or action in well over a year, I'm going to close this... feel free to open it again if either of you feel otherwise.
