### ISSUE TITLE
Use a module system

### ISSUE THREAD

**Issue by danvk** [danvk/dygraphs#453]
It's a bit ridiculous that we manage all these JS files [manually](https://github.com/danvk/dygraphs/blob/master/dygraph-dev.js). [browserify](http://browserify.org/) is fairly standard these days and solves the problem by adding a node.js-like `require` statement to JS.

One problem is that the various classes that Dygraphs defines don't map cleanly to individual files. For example, at least six or seven different JS files define methods on the `Dygraph` object.

- [x] Update developer documentation (`DEVELOP.md`)
- [x] Make sure copyright stays on `dygraph-combined.js`
- [x] Make sure `tests/*.html` doesn't break
- [x] Set module attributes on `Dygraph` for backwards compatibility, e.g. `Dygraph.dateTicker`
- [x] Update gallery
- [x] Get code coverage working
- [x] Remove gulpfile (& port gwt task over)
- [x] Set the `DEBUG` variable via `envify`
- [x] Get the `DygraphOptionsReference` checks working again
- [x] Migrate the remaining data handlers
- [x] Update tests
- [x] Update `dygraph-gviz.js`
- [x] Kill `dygraph-dev.js`

**Comment by danvk** [comment]
At this point dygraphs may as well jump straight to [ES6 modules][1] and webpack.

The dygraphs dependency graph is a bit of a mess, but I don't think it's going to be _too_ bad to untangle. Most files only depend on `dygraph-utils`. I've started a spreadsheet tracking this [here][2].

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
[2]: https://docs.google.com/spreadsheets/d/1Ynf1giJB_6OiGESDeMb1KAct-4Mh0we8EDekLfOsedE/edit?usp=sharing

**Comment by danvk** [comment]
The game plan here is going to be:

- Change files which set `Dygraph.Foo` to instead just export `Foo`. (e.g. `Dygraph.Interaction`)
- Change `dygraph-utils.js` to export functions/vars, rather that setting them on `Dygraph`. This will force most other files to be updated.
- Pull `Dygraph.DEFAULT_ATTRS` out into its own module.
- Build this all using webpack.

I'm not sure which bits of this can be done piecemeal, e.g. should I start by building & migrating just core dygraphs (no plugins, only the default data handler)?

**Comment by danvk** [comment]
This wound up being simpler than expected. There are still some loose ends, but I think success is in sight. I've added a checklist to the top of the issue.

**Comment by danvk** [comment]
WIP: https://github.com/danvk/dygraphs/compare/module

**Comment by danvk** [comment]
A few other notes:

- I'm using browserify, not webpack. We can switch to webpack independently of this change if we like.
- Since we're using babelify, we get access to all the ES6 features it supports, e.g. compact object literals.
- This will also let us depend on third party libraries should we choose to do so (e.g. [underscore][1]).
- I may take the opportunity to get rid of gulp. I'm not a fan.

[1]: http://underscorejs.org/

**Comment by reinert** [comment]
>> At this point dygraphs may as well jump straight to ES6 modules and webpack.

:+1: :+1: :+1: 

I would feel motivated to participate actively if that strategy would be adopted :)

**Comment by reinert** [comment]
> This will also let us depend on third party libraries should we choose to do so (e.g. underscore).

Is it really necessary? Third part dependencies for libs are not good idea in general. Unless the lib really depends on it (e.g. is a superset of it)

**Comment by danvk** [comment]
> > At this point dygraphs may as well jump straight to ES6 modules and webpack.

> :+1: :+1: :+1: 

> I would feel motivated to participate actively if that strategy would be adopted :)

If you check out the module branch, you can see the work in progress. Help with dygraphs is always appreciated, see the [contributors guide][1]. Probably the easiest way to jump in is by picking an issue that's labeled as a bug and fixing it (with a regression test).

> > This will also let us depend on third party libraries should we choose to do so (e.g. underscore).
> Is it really necessary? Third part dependencies for libs are not good idea in general. Unless the lib really depends on it (e.g. is a superset of it)

In the world of NPM, I don't see much trouble with it. For users who want to simply include `dygraph.min.js`, the dependencies will all be inlined and hidden. For users of browserify/webpack, NPM will handle the deps.

[1]: http://dygraphs.com/changes.html

**Comment by reinert** [comment]
>>> This will also let us depend on third party libraries should we choose to do so (e.g. underscore).

>> Is it really necessary? Third part dependencies for libs are not good idea in general. Unless the lib really depends on it (e.g. is a superset of it)

> In the world of NPM, I don't see much trouble with it. For users who want to simply include dygraph.min.js, the dependencies will all be inlined and hidden. For users of browserify/webpack, NPM will handle the deps.

I was not referring to the dependencies management. Instead, I worry about overloading the lib with a whole other lib that you may use a couple of features. (if that's the case)

**Comment by danvk** [comment]
I won't let dygraphs balloon, don't worry!

**Comment by reinert** [comment]
> I won't let dygraphs balloon, don't worry!
:+1:
