### ISSUE TITLE
Can't click "Edit in jsFiddle" -button in resize example on website.

### ISSUE THREAD

**Issue by jsyrjala** [danvk/dygraphs#458]
See http://dygraphs.com/gallery/#g/resize . Graph is overlayed on top of the "Edit in jsFiddle" -button, so button can't be clicked.

**Comment by kbaggott** [comment]
Any chance someone could add some margin to the chat div so I can close this?

**Comment by pshevtsov** [comment]
@danvk I've provided a fix for this in #729 
How to deploy in on site?
