### ISSUE TITLE
Redraws not happening when accelerated 2d canvas enabled in Chrome

### ISSUE THREAD

**Issue by zAlbee** [danvk/dygraphs#480]
This problem occurs with all graphs, including the main graph on the front page of dygraphs.com (NYC vs SF weather). 

- when moving the mouse over the graph, the dots do not move
- when clicking and dragging, the "shading" visualization is not seen
- when letting go of a click-drag, only the axes labels are updated; the graph itself doesn't change at all.

These all work properly for me in Firefox 30.0, and it used to work in Chrome too, but now it doesn't. I found that enabling the chrome flag "Disable accelerated 2D canvas" (`chrome://flags/#disable-accelerated-2d-canvas`) consistently fixes the issue, while disabling the flag reproduces it. So it's possible that it was always broken, but a recent version of Chrome just flipped this flag?

Note that I am not noticing any kind of graphical issue with other websites (as far as I can tell).

OS: Win 7 x64
Browser: Chrome 38.0.2125.111 m / Chrome 39.0.2171.65 m (both have the issue)
GPU: GeForce 9500M on a 5-year-old laptop

**Comment by zAlbee** [comment]
This no longer happens for me anymore. I guess either a Chrome or a driver update fixed it.

**Comment by danvk** [comment]
Glad it's working for you!
