### ISSUE TITLE
IE10/11 Compatibility

### ISSUE THREAD

**Issue by bwtaylor89** [danvk/dygraphs#510]
Hi there!

I've noticed that Dygraphs is not compatible with IE10 or IE11 when trying to load an external CSV file. It reports the error "SCRIPT5: Access is denied." But I've found where the issue lies.

It's trying to use an XMLHttpRequest() object to load the data, when it needs to use ActiveXObject('Microsoft.XMLHTTP'). If you include a simple browser check for IE10/11 so that it uses the ActiveXObject, it should work!

**Comment by danvk** [comment]
Closing this out due to inactivity. Feel free to reopen if you have more details.
