### ISSUE TITLE
Series with custom/error bars can't have color with transparency (i.e. rgba color)

### ISSUE THREAD

**Issue by mKlus** [danvk/dygraphs#517]
Series with custom/error bars can't have color with transparency (i.e. rgba color).

The cause: The Dygraph.toRGB_ function does not parse colors with transparency (rgba colors).

Example: http://jsfiddle.net/v8dt3nak/

Would be good to use a something similar to TinyColor to parse colors. https://github.com/bgrins/TinyColor

**Comment by danvk** [comment]
TinyColor is ~14k compressed—not so tiny in my book!

The current logic for computing the fill color is to set the alpha part of the series to [fillAlpha][1]. For a series with its own alpha value, what would you expect dygraphs to do? Override the alpha value? Multiply it?

[1]: http://dygraphs.com/options.html#fillAlpha

**Comment by danvk** [comment]
I can confirm that this did regress from 1.0.1, so it should be fixed in a point release.

**Comment by mKlus** [comment]
Great, thanks!
