### ISSUE TITLE
Reset on synchronized graphs failed

### ISSUE THREAD

**Issue by ghplink** [danvk/dygraphs#524]
In Synchronization example zoom y range in one graph by mouse drag. After that a double-click in another graph does not reset ranges. Even reset in first graph won't work anymore.
Defect is in version 1.1.0

**Comment by danvk** [comment]
The core issue here is that `resetZoom` (which is called when you double-click on a chart to zoom out) doesn't reset the y-axis zoom when it's been set programmatically. It only resets the x-axis zoom. This doesn't make much sense, but it's a behavior that I'm reluctant to change for a point release. This may have to wait for 2.0.

**Comment by danvk** [comment]
See #326

**Comment by danvk** [comment]
I think the right behavior is for double-clicking to be the same as calling `resetZoom`. And they should zoom out to the full range of the data on both axes.

The `isZoomedIgnoreProgrammaticZoom` option may be relevant here:

> When this option is passed to updateOptions() along with either the dateWindow or valueRange options, the zoom flags are not changed to reflect a zoomed state. This is primarily useful for when the display area of a chart is changed programmatically and also where manual zooming is allowed and use is made of the isZoomed method to determine this.

See http://dygraphs.com/tests/is-zoomed-ignore-programmatic-zoom.html
