### ISSUE TITLE
Unminified bower files

### ISSUE THREAD

**Issue by cthrax** [danvk/dygraphs#527]
Hi,

I've been using dygraphs for awhile and resolving via bower, and really like the library, but recently had to update from 1.0.1 to 1.1.0 and noticed in 1.1.0 that there are a number of datahandlers being concatenated to make dygraphs-combined, but that these datahandlers are not included in the bower package, in fact, they are explicitly ignored.

Distributing a minified prebuilt version is fine for anyone that is just using dygraphs, but integrating that into a larger build system becomes problematic, which is why bower strongly recommends not to include minified files (https://github.com/bower/bower.json-spec#main).

That aside, I have worked around that and am concatenating the files myself in my build system, but seeing the datahandlers in the dygraphs-combined, but not in the bower package I'm at a loss as to whether those are needed or not. For now, I'm just pulling the whole git repo, but it'd be nice to get clarification to see if I could get away with just the bower package.

Thanks for all your work on this!

If it'd be welcome, I'd happily spend some time refactoring the build system to use gulp so it's a little easier to get minified and non-minfied source out of all this, maybe even get karma running mocha tests through phantomjs.

**Comment by danvk** [comment]
I believe this was fixed in https://github.com/cthrax/dygraphs/commit/daab85060912edf8b14c7315a40b3cbe9e923c07?
