### ISSUE TITLE
Ability to load dyGraph using require.js

### ISSUE THREAD

**Issue by AlainBaslter** [danvk/dygraphs#531]
The "pros" recommend adopting a modular approach for loading Javascript libraries/modules.
For instance John Papa covers this topic at length in one of his KO classes on Pluralsight and there are many others.
The reason is to deal with the issue of module dependencies and loading order.
dyGraphs is a great library however it appears that it does not support AMD loading.
That makes it difficult to use it in the context of an application that is already using require.js for loading modules. I have no idea if it is possible and how to make DyGraphs work in this way. I read about shims and such but would not know how to apply this to DyGraphs.

The ability to load DyGraphs using AMD would be beneficial to developers.

**Comment by gulrotkake** [comment]
I use dyGraphs with requirejs, here's my config:

```javascript
require.config({
    paths: {
        'dygraphs':   '3rdparty/dygraph-combined-1.1.0'
    },
    shim: {
        'dygraphs': {
            exports: 'Dygraph,DygraphCanvasRenderer,DygraphLayout,DygraphOptions'
        },
    }
});
```

**Comment by AlainBaslter** [comment]
Ahhhh. Thank you so much for helping me out. I had a vague idea it had to do with shims but did not know how. That sure gets me going in the right direction. Thanks

**Comment by danvk** [comment]
I'm going to close this out—let me know if there's something else that dygraphs needs to do.
