### ISSUE TITLE
Zoom behaves oddly when valueRange contains strings 

### ISSUE THREAD

**Issue by polakko** [danvk/dygraphs#535]
When pulling data from external database, sometimes what we expect to be a number is actually a string in JS. When such accidentaly wrongly typed values are fed into dygraphs' valueRange option, it behaves oddly without a warning. The value range is properly displayed as the values where of a right datatype, so the mistake is not easily spotted. But everything fails when using vertical zoom for the first time, as it sends the user far out of scale.
See the JSFiddle:
http://jsfiddle.net/eM2Mg/5561/
and try vertical zooming.

Solution/proposal - parseFloat the valueRange, or else include a specific warning in the docs, perhaps print a warning in the console?

**Comment by danvk** [comment]
`valueRange` expects numbers. If you give it something else, I'm not sure why you'd expect it work.

**Comment by polakko** [comment]
Exactly, I would expect it not to work. But it pretends it does.
