### ISSUE TITLE
Dygraph.dateAxisLabelFormatter fails after switching from release 1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by bashlibrary** [danvk/dygraphs#536]
![fail](https://cloud.githubusercontent.com/assets/4864964/5897843/fc8ef582-a548-11e4-9ec8-6d906f411068.png)

**Comment by danvk** [comment]
Can you give some context? Preferably a repro via dygraphs.com/fiddle

**Comment by bashlibrary** [comment]
Finally I found that there was a wrong usage of the axis label formatter. sorry for that.
