### ISSUE TITLE
No more built-in drawPointCallback or drawHighlightPointCallback

### ISSUE THREAD

**Issue by bwtaylor89** [danvk/dygraphs#544]
Hi,

Since the most recent version was released, the built-in options for drawPointCallback and drawHighlightPointCallback no longer work, such as

drawPointCallback : Dygraph.Circles.TRIANGLE,
or
drawPointCallback : Dygraph.Circles.HEXAGON,

The points are always set to the default of circles.

**Comment by danvk** [comment]
`drawPointCallback` works fine. But Dygraph.Circles.TRIANGLE and friends have moved out of core dygraphs and into `extras`. If you still need them, you can source `extras/shapes.js`.
