### ISSUE TITLE
Does dygraphs support plot lines/bands?

### ISSUE THREAD

**Issue by crzrcn** [danvk/dygraphs#545]
Does dygraphs have a similar feature to this: http://www.highcharts.com/docs/chart-concepts/plot-bands-and-plot-lines?

**Comment by chetan** [comment]
Bands are somewhat supported, see this example: http://dygraphs.com/gallery/#g/highlighted-region

**Comment by danvk** [comment]
I believe #537 addresses this.

**Comment by crzrcn** [comment]
No plot lines support thought, right?

**Comment by apraveen** [comment]
Any plans to support plot lines in future?

**Comment by kbaggott** [comment]
Take a look at #215, this works for me as a work around, closing this ticket...open to a PR for an enhanced version of this if anyone wants to.
