### ISSUE TITLE
why adds five hours a timestamp field

### ISSUE THREAD

**Issue by montes2012** [danvk/dygraphs#549]
hello, from a database and get timestamp fields to plot adds 5 hours

why?

![fecha_and_hora](https://cloud.githubusercontent.com/assets/3384541/6235919/0051cb28-b6b4-11e4-9023-bdaf1aeb4b73.png)

![fecha_hora_2](https://cloud.githubusercontent.com/assets/3384541/6235922/06df2530-b6b4-11e4-888e-4948979d03bc.png)

**Comment by danvk** [comment]
Maybe something to do with timezones? http://dygraphs.com/options.html#labelsUTC

**Comment by montes2012** [comment]
labelsUTC: false,

working
