### ISSUE TITLE
Synchronizer fails on remotely-loaded data

### ISSUE THREAD

**Issue by RussNelson** [danvk/dygraphs#551]
This jsfiddle works: http://jsfiddle.net/q0L345a8/2/
If you replace mydata with "http://rths.us/mydata.cgi", it ceases to work even though the exact same data is being loaded.

Chromium Version 40.0.2214.111 Ubuntu 14.04 (64-bit)

**Comment by danvk** [comment]
Can you explain what you mean by "fails"? I believe this is working perfectly: http://jsfiddle.net/q0L345a8/3/

**Comment by RussNelson** [comment]
It's not synchronized. Also, (and this may not be related), I get this error in the console:

Uncaught TypeError: Cannot read property 'clear' of undefined which is complaining that the plotter_ value is undefined(!).

**Comment by danvk** [comment]
Interesting, zooming/panning on the first chart adjusts all the others, but not vice versa.

Here's what I think is going on: the dygraphs constructor blocks until the chart draws when you pass it data inline, but not when you pass remote data. I'll bet if you wait to synchronize until the `ready` callback fires for all your dygraphs, then it will work.

Really this should be handled by the synchronizer, though. Thanks for the bug report.

**Comment by RussNelson** [comment]
Hmmmm...... but if I click on either checkbox, that *ought* to invoke the synchronize() function, correct? So shouldn't that have the same effect as "wait[ing] to synchronize until the ready callback fires for all your dygraphs"? Yet it doesn't. Am I misunderstanding how it works or what you suggest?

**Comment by RussNelson** [comment]
The error message seems to be of relevance. I tried putting a breakpoint on the beginning of the update() function, and it's not getting called in the /3/ jsfiddle.

Ah! That explains why my previous comment is wrong. The synchronize() call is crashing, so the update never gets executed, so you can fiddle with the checkmarks all day long, and nothing will happen.

**Comment by RussNelson** [comment]
I believe I have a fix. Will generate a pull request shortly. http://jsfiddle.net/q0L345a8/4/

**Comment by danvk** [comment]
Fixed by #552
