### ISSUE TITLE
Synchronization extension skips on other charts

### ISSUE THREAD

**Issue by userlite** [danvk/dygraphs#554]
On the example on the website, the synchronization misses intervals as you move around. You'll notice as you slide around, the chart you're hovering over updates each interval. But the other charts skip intervals. You can see the problem here:

http://dygraphs.com/gallery/#g/synchronize

Notes:
* Seems to consistently skip the same intervals between page reloads
* Easy to see if you hover over the highest peak in the chart
* Same behavior in Chrome and Firefox on Windows.
* For my charts (like the example) I'm using very regular data-- the same exact intervals for each chart. They are each one day so it's not like the charts are off by hours or minutes or seconds.

**Comment by danvk** [comment]
(I can confirm this)

**Comment by danvk** [comment]
I wonder if it's a bug in `dygraphsBinarySearch`?

**Comment by danvk** [comment]
Bingo! Lesson: never write binary search yourself. (I've used this as an interview question before, but apparently I can't do it myself.)

**Comment by userlite** [comment]
@danvk Thanks for working on this. Just applied it and it's now fully awesome. 

I would have helped more but my binary search skills are a little rusty ;-)

**Comment by danvk** [comment]
apparently my binary search skills are rusty, too!

**Comment by tk5ep** [comment]
Hi All,

I have the same problem as mentioned above. I'm not familiar with Github... :-(
Where can i find a corrected version of syncronizer.js and/or correct the mentioned problem ?

**Comment by userlite** [comment]
One character should do the trick:

https://github.com/danvk/dygraphs/commit/d5ce61bccb248d7e60239c18068c2ba3aecdb3ec

On Mon, May 25, 2015 at 5:48 AM, Patrick EGLOFF <notifications@github.com>
wrote:

> Hi All,
>
> I have the same problem as mentioned above. I'm not familiar with
> Github... :-(
> Where can i find a corrected version of syncronizer.js and/or correct the
> mentioned problem ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danvk/dygraphs/issues/554#issuecomment-105188765>.
>



-- 

David Ogden
(919) 589-2539
david@userlite.com

**Comment by tk5ep** [comment]
Indeed !!

Thanks !
