### ISSUE TITLE
Artifacts due to lossy compression of stacked chart with gaps

### ISSUE THREAD

**Issue by Dronablo** [danvk/dygraphs#555]
If I try to draw a stacked chart with gaps, it produces artifacts:
![gaps_bad](https://cloud.githubusercontent.com/assets/5829111/6524101/22bee140-c407-11e4-9a84-0ca7b3df2cb6.PNG)
Gaps in the data are formed like this way:

x values | y values
-------- | --------
1 | 10
2 | 15
3 | 10
4 | 0
9 | 0
10 | 10

See the gap between 4 and 9. In the sample images it's much more points of course.
I've managed to fix it by changing code in DygraphCanvasRenderer._fastCanvasProxy.addAction, line 1734 in dygraph-combined-dev.js:
replace "flushActions();"
with "flushActions(rx - lastRoundedX>1);"
So, it produces following graph without any noticable performance overhead:
![gaps_good](https://cloud.githubusercontent.com/assets/5829111/6524222/639bf9d6-c408-11e4-8192-8be2843f2c2a.PNG)

**Comment by danvk** [comment]
It would help if you could share a link that reproduces this with dygraphs.com/jsfiddle. Thanks for the suggested fix.

**Comment by danvk** [comment]
This is the same as #558, which includes a repro. Closing this issue in favor of that one.
