### ISSUE TITLE
Range synchronization

### ISSUE THREAD

**Issue by mirroj** [danvk/dygraphs#562]
I think range synchronization should by implemented another way. If a have for example three graphs to be synchronized: 
G1 range: 0 to 5 
G2 range: 4 to 8
G3 range: 7 to 10
I expect after synchronization they should all have range 0 to 10. In current implementation graphs will have some random range. Two of them will have same range but that is not what I expect.

Solution to this is only finding minimum from range minimes and maximum from range maxims and set this range to all graphs.

**Comment by danvk** [comment]
Can you give some context or an example link? Is this an issue about extras/synchronizer.js?

**Comment by mirroj** [comment]
Yes. It's about extras/synchronizer.js.

For example this:
http://jsfiddle.net/NtBPk/533/

When I synchronize graphs I dont want do "copy" range of G1 to other graphs. In example above you can see that when sync is checked, G3 "disappears" because it has completely diferent range than G1 (you must find it up/down with shift+click).

So my suggestion is to make unions of these ranges so when you synchronize range in example above you will see all three graphs. Because united range in example will be from -3 to 3.

**Comment by danvk** [comment]
You can pass [`range: false`][1] if you don't want to synchronize the ranges. If you want to do something fancier, you'll need to muck around with `synchronizer.js`.

[1]: https://github.com/danvk/dygraphs/blob/ef44ba44d235f6e6fbbc3ae481661380cb6514be/extras/synchronizer.js#L31

**Comment by danvk** [comment]
I'm going to close this out. Feel free to reopen if I misunderstood the issue.
