### ISSUE TITLE
labelsKM{B,G2} behave oddly for values in (0, 1)

### ISSUE THREAD

**Issue by danvk** [danvk/dygraphs#571]
`labelsKMB` has no effect on values between 0 and 1. You might expect it to use "m", "µ" and "n" lowercase prefixes.

`labelsKMG2` does something bizarre. In `testSmallLabelKMG2` I see these labels:

```
['0', '0.48u', '0.95u', '1.43u', '1.91u']
```

These aren't even multiples of powers of two. And it's unclear to me whether those prefixes are used for binary units (e.g. "u" to mean 2^-20).

**Comment by mirabilos** [comment]
Working on this (see #994 comments), but this is really weird, there must be some kind of data smoothing going on?

With my current WIP code, these are just printed as (decimal, supposedly!) scientific (and, oh, why does this use the lowercase `e` for this, this reads so weird), and Travis-CI logs:

       [
         "0"
         "4.77e-7"
         "9.54e-7"
         "1.43e-6"
         "1.91e-6"
       ]

The median is supposed to be the second value IIUC.

    .0000009540 // out
    .0000010000 // in

The delta is really small, but it is there…

**Comment by mirabilos** [comment]
It’s a bug in `numericTicks()`.

**Comment by mirabilos** [comment]
tbh I’m not convinced in “small 2-based” units for the axes at all, after all 0.5, 0.25, etc. are the corresponding powers of two

**Comment by mirabilos** [comment]
Hm, or maybe it’s _not_ a bug in `numericTicks()` and the input values should just be the expected ones (e.g. `2^⁻ˣ`)…

**Comment by mirabilos** [comment]
Yeah, I guess it’s just the test.
