### ISSUE TITLE
Console is no longer allowed to be written to

### ISSUE THREAD

**Issue by tyduptyler13** [danvk/dygraphs#575]
The polyfill at the top of Dygraphs no longer works as is. Chrome (43.0.2342.2 dev-m) has locked the console object and prevents writting to its members. This causes Dygraphs to fail immediately.

```
(function(con) {
  'use strict';
  var prop, method;
  var empty = {};
  var dummy = function() {};
  var properties = 'memory'.split(',');
  var methods = ('assert,clear,count,debug,dir,dirxml,error,exception,group,' +
     'groupCollapsed,groupEnd,info,log,markTimeline,profile,profiles,profileEnd,' +
     'show,table,time,timeEnd,timeline,timelineEnd,timeStamp,trace,warn').split(',');
  while (prop = properties.pop()) con[prop] = con[prop] || empty;
  while (method = methods.pop()) con[method] = con[method] || dummy;
})(this.console = this.console || {}); // Using `this` for web workers.
```

The above needs to be changed so that it does not modify the console object.

**Comment by danvk** [comment]
Where are you getting dygraphs from? I've updated the console polyfill and
apparently chrome he been updated as well.

**Comment by tyduptyler13** [comment]
I am currently using the cloudflare CDN.

Just tested the issue again after a chrome patch (43.0.2351.3 dev-m) and the issue seems to be gone.
