### ISSUE TITLE
Performance problem on initial display

### ISSUE THREAD

**Issue by mjanda** [danvk/dygraphs#580]
Hello,
when I hover cursor above initially loaded chart and move it left/right, legend display seems choppy. If I zoom in and back out, it start to feel much more responsive.

It happens even on chart that is on http://dygraphs.com/ homepage, so it shouldn't be a problem with my specific config and/or data set.

Chrome JS profiler shows that all calls take more or less the same time, but before zooming, there is a lot of "idle" in between. This image shows similar mouse movement before/after zooming in and back out.

![dg](https://cloud.githubusercontent.com/assets/652954/7113571/5555b44e-e1d5-11e4-8004-2f34d7e8c4b0.png)

Calling updateOptions (with the same data) after drawing chart fixes the issue.

// Chrome 41.0.2272.118 (64-bit), Linux

**Comment by danvk** [comment]
I'm not quite sure what you mean by "choppiness". Maybe you could post a video of the effect? I'm on Chrome 42, and hovering over the chart on dygraphs.com is pretty smooth both before & after zoom.

**Comment by mjanda** [comment]
I've added fps meter inside highlightCallback and moving mouse left/right, I get around 10-20fps. Zoom in and out...and I'm getting 50-100fps on the same dataset (trying to move the mouse roughly the same speed).

I'm not sure if it would be noticable on video...it's barely noticable this way.

**Comment by danvk** [comment]
Are you talking about the Chrome Dev Tools FPS meter? I'm seeing 50-60fps consistently before & after zoom on that.

**Comment by mjanda** [comment]
I've used http://darsa.in/fpsmeter/ calling meter.tick() inside highlightCallback and sending meter.fps to console.

Now, I've tried dev tools fps meter on dygraphs site and it seems the same.
![dg1](https://cloud.githubusercontent.com/assets/652954/7120659/df7d58d2-e20e-11e4-90ec-ec7c464264b7.png)

btw: didn't even know about dev tools fps tool, nice.

**Comment by mjanda** [comment]
And I'm seeing the same behavior on completely different machine (Chrome 41, Windows Vista)

**Comment by mjanda** [comment]
https://www.youtube.com/watch?v=1Ro6h_hJs1k

**Comment by danvk** [comment]
Interesting. That bears no resemblance to the behavior I see. I'm on Chrome
42. Could you try using that (might require switching to the beta channel).

**Comment by mjanda** [comment]
You're right, 42 works ok.

**Comment by danvk** [comment]
I'm going to close this out unless others can reproduce.
