### ISSUE TITLE
Use native browser APIs for dashed lines

### ISSUE THREAD

**Issue by mKlus** [danvk/dygraphs#599]
Chrome, IE11, Opera support the following APIs for dashed lines:

CanvasRenderingContext2D.prototype.setLineDash
CanvasRenderingContext2D.prototype.getLineDash
CanvasRenderingContext2D.prototype.lineDashOffset

https://msdn.microsoft.com/en-us/library/ie/dn265063(v=vs.85).aspx
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash

http://www.rgraph.net/blog/2013/january/html5-canvas-dashed-lines.html#introduction

You could add polyfill for other browsers.

**Comment by danvk** [comment]
Dupe of #379

**Comment by mKlus** [comment]
Do you have a time frame for this fix?

**Comment by danvk** [comment]
I don't. Pull requests would be most welcome. Barring that, I'm not aware of any existing polyfills for `setLineDash`. Finding (or writing) one would be hugely helpful as well.
