### ISSUE TITLE
CSV is out of order; order it correctly to speed loading

### ISSUE THREAD

**Issue by zulander1** [danvk/dygraphs#604]
i am loading a large amount of data (30K) in to the gird, after verification, i've validated the order of the date/time column they are in order, however i keep getting "CSV is out of order; order it correctly to speed loading."

the data is being loaded by Json as a CSV, not too sure if it is a bug or not !\

http://jsfiddle.net/ve8mzhen/11/

look at csv:
https://www.dropbox.com/s/10lx9i7t0yg8ryv/example.csv?dl=0

**Comment by danvk** [comment]
Can you provide a working jsfiddle? I get a same origin error on yours.

**Comment by zulander1** [comment]
I would like to but i can't there is 30k data and i am getting memory overflow ;(,i've tired to do a direct link to the csv file but can't getting Cross-Origin XMLHttpRequest exception !!! So i guess you would have to download the csv file and run it on your machine !

thank's

**Comment by danvk** [comment]
Sorry, I can't help you without a repro.
