### ISSUE TITLE
Hairlines doesn't works 

### ISSUE THREAD

**Issue by cemadj** [danvk/dygraphs#606]
Hi,
Im trying to use the extra plugin Hairlines. i tested the example on Dygraphs repository, but i always have an error : TypeError: undefined is not a function
    at Dygraph.Plugins.Hairlines.hairlines.createHairline.
I don't know why , i have just made a copy/paste...
Can you please help me?
Thanks.

**Comment by danvk** [comment]
are you sourcing `hairlines.js`? I can't help you without example code.
