### ISSUE TITLE
dynamic update

### ISSUE THREAD

**Issue by sgomezc** [danvk/dygraphs#609]
Hi,

I am using dygraphs to graph a set of series ('live data'). This series are received from the server (ajax) and the user can decide in each moment what serie or series want to see (get from the server & see it).

to be brief:

```javascript

var data = []
var dlabels= ['Date','first_serie']// (initial)

  var g = new Dygraph(document.getElementById("div_g"), data,...)

   window.intervalId = setInterval(function() {
                   //Use case 1: user doesn't select any new serie
                    data.push([new Date(), first_serieValue]);

                   //Use case 2: user select series, i.e. second_series, then
                  data.push([new Date(), first_serieValue,second_serieValue]);
                  dlabels.push('second_serie')

                       g.updateOptions( { 'file': data, 'labels':dlabels} );
   }, 5000);
```
After testing this approach i realised that the function parseArray is checking the number of labels and data using the first element of the array 'data', so i have put ```data[data.length-1].length``` instead of ```data[0].length``` to avoid the error. --> ```    if (num_labels.length != data[data.length-1].length) ```

Then, i don't get any error but dygraphs is drawing only the series that i have specified at the beginning. 

How could i implement the approach of adding/removing dynamically series(dynamic series) to the current graph?

Obviously, I want to avoid deleting the whole graph and reload it again. 
Thanks in advance!

**Comment by mkirkor** [comment]
You can't add arrays of different length, they must all have the same number of elements for the series to display. I suggest that you re assign data's value instead of pushing into it

**Comment by sgomezc** [comment]
I can't re assign data's value because usually i have array[2] because user only want to see to values and then he probably want to add new data, array[3]. So i can't re assign...
