### ISSUE TITLE
How to NOT synchronize the Y axis ?

### ISSUE THREAD

**Issue by tk5ep** [danvk/dygraphs#612]
Sorry to post here, but i couldn't find a better place... Github is really puzzling me !

Is there a way to NOT synchonize the Y axis ? I have very different Y axis scales and synchonizing makes the out of range curves disappear.
 
Thanks,

**Comment by mkirkor** [comment]
You can set the valueRange. Put null as value if you want it to synchronize, or a value if you don't want
g.updateOptions({
                valueRange: [yaxisLow, yaxisHigh]
            });

**Comment by tk5ep** [comment]
Hi mkirkor

I'm not sure if i understood...
I set a valuerange to y on my second graph on which the line disappears, but this didn't help...
When i synchronize, i still changes the range... 

Tried both, setting a value or null... Did this in the graph options, not on upgrade as i don't know how to do this... (still learning)
Thanks

**Comment by mkirkor** [comment]
Can you post a code sample or jsfiddle? I'm not sure what you are trying to achieve

**Comment by tk5ep** [comment]
Thanks for your attention,

Sorry, i not familiar with jsfiddle . You can look on my test pages...
First without synchro : 
http://www.egloff.eu/apaguard/test1.php

With:
http://www.egloff.eu/apaguard/test2.php

**Comment by mkirkor** [comment]
Met ton code de synchronisation :)

**Comment by mkirkor** [comment]
Met zoom:false et met un valueRange comme je t'ai dit tantot ;)

**Comment by tk5ep** [comment]
Hi,

Just to be sure, i did set a valueRange to both graphs, but this does not help.
Only the one on the first graph has an effect on the second. If set, the second one does not work.
I'm still loosing my red curve on the second one, has it is out of range.

I modified this on second link. First one is w/o any range...

Sorry... It would be easier to have a parameter in the synchronizer script.

**Comment by mkirkor** [comment]
you need to set zoom false in your synchronize parameters.

**Comment by tk5ep** [comment]
Okkkkkkkkkkkay !
Now i got it... I was changing this at a wrong place...
It works, but of course i lost the zoom sync...

In the synchronizer.js file i found this:
* You may also set `range: false` if you wish to only sync the x-axis.
* The `range` option has no effect unless `zoom` is true (the default).

A bit confusing to me... Should'nt it be better "no effect if 'zoom' is true."

Btw setting ONLY zoom to false is enough...  range has no effect, so useless ?
I don't know if it is possible to make range : false work but still keeping the zoom sync..

I found a similar post to mine on groups.Google, asking for the same and Danvk answered .
https://groups.google.com/forum/#!topic/dygraphs-users/92VTmVkv7iI

Thanks !

**Comment by mkirkor** [comment]
Maybe you could preserve the zoom sync with a hacky way using ZoomCallBack

**Comment by tk5ep** [comment]
I'm not clever enough to do that... :-(
I'm only a hobby programmer.

Thanks,

**Comment by tdussmann** [comment]
@tk5ep as I understood the description in synchronizer.js:
You can synchronize x-Axis, but not y-Axis (=range, maybe a better name would by yRange?) by doing this:
```javascript
Dygraph.synchronize(dygraphs, {zoom: true, selection: true, range: false});
```
I.e. you set `zoom` to true (or not: default) and both, x- and y-axis will be synchronized. 
And only if `zoom` is true, `range=false` will have an effect, since it will then _take away_ y-synchronization again .
This works as stated for me.

**Comment by tk5ep** [comment]
Hi tdussmann,

I tried your suggestion, but it doesn't work. zoom NEEDS to be false, otherwise the y axis are synchronized (have same values) despite the fact that each graph has his onw valuerange set...

I'm not familiar with Github but i understand there is a 1.1.1 version of Dygraphs. I couldn't find where it is offered ti download...
Thanks,

**Comment by stanhu** [comment]
v1.1.1 of Dygraphs added the `range` option:

https://github.com/danvk/dygraphs/blob/master/src/extras/synchronizer.js#L156

It looks like it was just released:

https://github.com/danvk/dygraphs/releases

**Comment by stanhu** [comment]
Actually, v1.1.1 doesn't appear to have this option:

https://github.com/danvk/dygraphs/blob/v1.1.1/extras/synchronizer.js#L41

It looks like the only way to get this option is to use master.

**Comment by tk5ep** [comment]
OK thanks,
Quite strange ... I will try the master, but does this one have the search bug corrected.

Is there any reason why the range option has been removed ?

**Comment by stanhu** [comment]
It wasn't removed; it's just that v1.1.1 is quite a bit older version than master. Any particular reason, @danvk?

**Comment by tk5ep** [comment]
OK,

I made a cut and paste of the master code and it's not synchronizing at all ... 
Back to my older version.
Where can i download the master synchronizer.js file ? I must admit that i'm a bit puzzled with the Github philosophy... :-(

**Comment by tk5ep** [comment]
Hi, 
Is there any chance to see this feature added (or bug corrected) ?
Dygraphs is losing a LOT of interest if it is impossible to synchronize without having the possibility to have different Y axis.
Losing zoom selection to correct this is even worse..

Thanks,

**Comment by tdussmann** [comment]
@tk5ep 
OK, I will give it another try then. It is definitely not impossible, as I had successfully enabled synchronizing x-Axis while not synchronizing y-Axis. It works for me with both dygraphs 1.1.0  and 1.1.1 (the version currently available for download on dygraphs.com) 

I downloaded the synchronizer.js file [from the github repo](https://github.com/danvk/dygraphs/blob/master/src/extras/synchronizer.js). 
Here, click on `Raw` in the top right corne and save the resulting javascript file. Or right-click on `Raw` and select save-as. 

I can achieve the desired result, as I understand it, like this: 
    Dygraph.synchronize(g1, g2, g3, { selection: false, zoom: true, range: false });

Just make sure that sychronizer.js gets loaded and the plugin/extra should work with both Dygraph versions mentioned above.

**Comment by danvk** [comment]
`master` and the 1.1.x branch diverged a while back. We made breaking changes which dropped support for older browsers.

If you don't need older browsers, you can build your own copy of dygraphs from `master` and you'll get the `range: false` option for the synchronizer. I believe you can't use the `synchronizer.js` from head because it relies on some utility methods that were added off the 1.x branch.

**Comment by tdussmann** [comment]
ok, thanks @danvk , i wondered if the `synchronizer.js` from head would be compatible with my release build, however it works well apart from some weird behaviour, which propably is not related to synchronization itself. 
at least the synchronization methods run without any errors and I'm pretty sure I downloaded this "extra" not more then 3 months ago... 

I just did a 

and for me it seems that all that changed regarding x and / or not y synchronization was: 
```python
        for (var j = 0; j < gs.length; j++) {
          if (gs[j] == me) continue;
          gs[j].updateOptions( {
            dateWindow: range,
            valueRange: yrange
          });
```
to
```python
        if (syncOpts.range) opts.valueRange = me.yAxisRange();

        for (var j = 0; j < gs.length; j++) {
          if (gs[j] == me) continue;
          gs[j].updateOptions(opts);
```

range is determined by yAxisRange() in both cases (this is where I get wrong values somehow), but it works just the same, except that range is now an additional configuration. 
As I see now, selection synchronization changed as you said, that's propably why it only worked partially. But since I have this disabled I don't see any issues with this combination. 
For @tk5ep  it would be best to port those range sync changes to his dygraphs version.

**Comment by tk5ep** [comment]
Hi,

Thanks for your interest and answers.

I downloaded the synchronizer.js from the master and the range options seems to work now.

I looked in the code and the mods suggested by tdussmann is there as well as the range option.

Unfortunately, i lost the roller which is only vivible under the mouse, not anymore on the other graph...

In my file, i have:
var sync = Dygraph.synchronize(g1,g2,
								{range:false,selection:true,zoom:true}  );

Thanks

**Comment by danvk** [comment]
It seems like this has been resolved? Feel free to reopen if there's a specific issue.

**Comment by stanhu** [comment]
Will there be a release soon for all the changes on `master`? I'm still using a custom build until a subsequent version is released after 1.1.1. Thanks!

**Comment by danvk** [comment]
No plans to cut a release in the immediate future.

**Comment by AlexeyRomanchenko** [comment]
> @tk5ep as I understood the description in synchronizer.js:
> You can synchronize x-Axis, but not y-Axis (=range, maybe a better name would by yRange?) by doing this:
> 
> ```js
> Dygraph.synchronize(dygraphs, {zoom: true, selection: true, range: false});
> ```
> 
> I.e. you set `zoom` to true (or not: default) and both, x- and y-axis will be synchronized.
> And only if `zoom` is true, `range=false` will have an effect, since it will then _take away_ y-synchronization again .
> This works as stated for me.

it helped for me

**Comment by davidporter** [comment]
Which version of dygraphs.js and synchronize.js do I need to get this to work?

**Comment by ensconce** [comment]
> Which version of dygraphs.js and synchronize.js do I need to get this to work?
> 
> (I am using both now and I see the range: false option and have it set but my graphs reset the y-range when I zoom another graph)

This is the case for me as well, zooming results in also zooming the Y-axis even though using these settings

`{zoom: true, selection: true, range: false}`

Any hints to get this working properly?
Using version 2.1.0

**Comment by dougwo** [comment]
I too am using 2.1.0 and cannot get it to work. In all cases it syncs the y axis. I also need double-click reset to go back to the original value ranges for each graph.

**Comment by dougwo** [comment]
Aha! Here is how I got it to work got 2.1.0. 

var sync = Dygraph.synchronize(gs, {
       zoom: true,
       selection: true,
       range: false
  });

Then, on the drawcCallback, I commented out the valueRange call. 

                    drawCallback: function(me, initial) {
                        if (blockRedraw || initial) return;
                        blockRedraw = true;
                        var range = me.xAxisRange();
                        var yrange = me.yAxisRange();
                        for (var j = 0; j < 4; j++) {
                            if (gs[j] == me) continue;
                            gs[j].updateOptions( {
                                dateWindow: range,
                                //valueRange: yrange
                            });
                        }
                        blockRedraw = false;
                    }
