### ISSUE TITLE
Using dygraphs from webpack

### ISSUE THREAD

**Issue by bbirand** [danvk/dygraphs#616]
I'm trying to move all my JS into webpack modules. I am trying to figure out a way to use dygraphs using the CommonJS `require` call. When I try

```
var Dygraphs = require('dygraphs);
```
I see the error:
```
ReferenceError: DygraphCanvasRenderer is not defined
```

Is this a supported way of using Dygraphs?

**Comment by davidebianchi** [comment]
I'm having the same problem for a [project I'm working on](https://github.com/innowatio/iwwa-front). From a brief look at the code it seems like the "non standard" build process may be the cause of it. Would you consider a PR to introduce browserify or webpack as build tools (as per #453)? Would it be too complex for someone new to the codebase?

**Comment by danvk** [comment]
dygraphs isn't well structured in terms of modules. Converting the whole project to use `require`/browserify is a noble goal but would be a major undertaking.

You might have better luck getting `require('dygraphs')` to pull in the pre-built `dygraph-combined.js` file.

**Comment by danvk** [comment]
Folding this in to #453
