### ISSUE TITLE
Chromium not drawing series when hardware accelerated (VirtualBox)

### ISSUE THREAD

**Issue by Xan-Kun** [danvk/dygraphs#618]
This is not really an Issue of dygrahp, but maybe it will help others and we can collect more information.
There is an old Issue
https://code.google.com/p/chromium/issues/detail?id=84882
That has been fixed so far, but I discovered recently the exact same behaviour (labels etc. work, except the series and the grid is not drawn) in the most recent version of chrome, 43 (It seems to work with 42). First I thought, it was a problem of dygraph/chrome, but it only happens when chromium runs inside a VirtualBox. So maybe the problem itself is more related to the VirtualBox hardware acceleration?

As I said, no problem with dygrapg,everything works fine outside the VirtualBox with hardware acceleration.

**Comment by danvk** [comment]
I'm going to close this out since I haven't heard anything else about it.
