### ISSUE TITLE
Is it easy to use svg backend for drawing? Sometimes we want to export a static vector graph.

### ISSUE THREAD

**Issue by cailiang9** [danvk/dygraphs#623]

**Comment by danvk** [comment]
No, dygraphs makes extensive use of `<canvas>`, so this wouldn't be a simple matter.

You might have better luck exporting a PNG. There's been some work [here](http://cavorite.com/labs/js/dygraphs-export/) and discussion [here](https://groups.google.com/forum/#!topic/dygraphs-users/whcMjtBE7s0).

**Comment by cailiang9** [comment]
Thanks for your quick reply! But I think the underlying elements are just arcs, rectangles, lines, points. We only need to translate these. The texts are already good enough. 
Highcharts is already good for SVG. But not totally free.

**Comment by danvk** [comment]
Your best bet then is to find or write an alternative implementation of the canvas API that writes out to SVG. Godspeed, and please let us know if you get this to work!

**Comment by cailiang9** [comment]
there really is a lib: http://svgkit.sourceforge.net/SVGCanvas.html
I think we don't expect a full support of canvas api, but a subset which dygraph uses most frequently.

**Comment by cailiang9** [comment]
I think this svgkit.js should not be combined with dygraph. Because it will make dygraph too fat. And svg will be slower. I think we can simply require svgkit.js when exporting to svg graph. Because this is a useful but less frequent function (mainly for static publications).

**Comment by kovasap** [comment]
@cailiang9 did you ever get this to work?  Or what did you settle on as your solution for svg export?

**Comment by cailiang9** [comment]
No. plotly or https://vega.github.io/vega-lite/examples/ could work

**Comment by kovasap** [comment]
Ok, thanks for the update!

**Comment by Uknods2** [comment]
I'm hacked these are not my comments and I'd love free of this mess.
