### ISSUE TITLE
how to generate dygraph-combined.js

### ISSUE THREAD

**Issue by mrin9** [danvk/dygraphs#624]
I am trying to make some changes to dygraph src , to suite my case. How should I generate a dygraph-combined.js 

I dont find the generate-combined.sh script which is used inside push-to-web.sh ?

**Comment by mrin9** [comment]
figured out the generation process so closed the issue, but still there is some dead code refering to some non existing scripts

**Comment by danvk** [comment]
Which script are you thinking of?

**Comment by mrin9** [comment]
there is a file under scripts folder push-to-web.sh which has reference to generate-combined.sh, I guess we moved away from these, but they still exist in the codebase
