### ISSUE TITLE
Link broken in synchronize gallery

### ISSUE THREAD

**Issue by tk5ep** [danvk/dygraphs#627]
FYI,

The following link :
https://github.com/danvk/dygraphs/blob/master/extras/synchronizer.js

in the Dygraphs gallery gives a 404 page.

Cheers,

**Comment by pshevtsov** [comment]
It seems it was fixed in 9ee99eb

Needs to be redeployed. @danvk?

**Comment by danvk** [comment]
I just fixed this by hand on the site.
