### ISSUE TITLE
Dygraph inside a jquery.ui tab element does not always draw correctly

### ISSUE THREAD

**Issue by rjparker** [danvk/dygraphs#631]
I have dygraphs on jquery.ui tabs that draw as if max and min values for scaling are the same. (The data points seem to pile up in the center of the graph. 

If I refresh the display by changing the browser scale (CTRL+ or CTRL-), the graphs draw correctly. I have drawn these graphs with the tabs hidden. I have tried refreshing the graphs an a tab activation event. 

I don't find this to be an issue of missing components. All js is loaded at the top of the html code and there is a leisurely pause before any tab is activated. 

I will speculate and ask: what in the browser environment (and possibly in the tab environment) is necessary for dygraph to scale correctly - specifically, what would be reinitialized when the browser window is rescaled with CTRL+ or CTRL -?

Thank you in advance for tips/suggestions.

**Comment by mkirkor** [comment]
can you post a jsfiddle showing the problem?

**Comment by rjparker** [comment]
I will. However I have never used it. I will come up to speed on jsfiddle over the weekend. Thanks

**Comment by rjparker** [comment]
OK. here is my first fiddle. This simplified example is how the line graph should and DOES display after altering the browser magnification with CTRL +/-. This is the end goal that I want to embed in a jquery.ui tab. 

https://jsfiddle.net/rjparker/4kw7n85u/20/

I will next try another fiddle to put this in the .ui tab wrapper. May take a bit, and may not be able to reproduce the exact failure, since it is somewhat intermittant...

**Comment by mkirkor** [comment]
does this work for you? 
http://jsfiddle.net/CnEUh/1491/

**Comment by rjparker** [comment]
Your example works 100% of the time in my browser. My CSS is very different. yours is much simpler, and I may have too many constraints on the DIV with some of my positioning CSS. I am suspicious becuase my example WITHOUT tabs did not draw 100% of the time. Thank you for the baseline. let's see if simplifying CSS clears everything up. Unless it is inappropriate, I will leave this thread open for a (hopefully final) update.

**Comment by mkirkor** [comment]
Your jsfiddle didn't load all the time because you didn't include the javascript file in the resources. It has nothing to do with your code. But yeah, change the css something must be conflicting. Use my jsfiddle if you want to modifiy or post updates

**Comment by danvk** [comment]
I'm going to close this out, it seems like more of a troubleshooting thread than a dygraphs bug thread.
