### ISSUE TITLE
Printing doesnt work correctly

### ISSUE THREAD

**Issue by b-pos465** [danvk/dygraphs#632]
If i try to print a dygraph it wont be shown on my pdf. (y and x axis get print but no data)

However, it works after re sizing the graph. I've tried it with different examples on your page like:

http://dygraphs.com/gallery/#g/range-selector

I'm using Chromium Version 43.0.2357.81 Ubuntu 14.04 (64-bit).
I got this issue with the latest version of Chrome as well. On another computer with the same Chrome version it works without problems.

**Comment by danvk** [comment]
I just printed the range selector gallery page in Chrome and it worked fine.
