### ISSUE TITLE
Strange behaviour in time display

### ISSUE THREAD

**Issue by tk5ep** [danvk/dygraphs#638]
Hi,

I noticed that there is a additionnal colon (:) sign behind the date or time displayed. Also, when the time is round ( 17:00:00 , the seconds disappear...

**Comment by FrEaKmAn** [comment]
Can you show the image?

**Comment by tk5ep** [comment]
At least someone is not on holiday... ;-)

You can see the added colon on all the demos in the gallery !

On my test page, you can see how the seconds disappear when the are at 00.
http://www.egloff.eu/apaguard/test.php

Thanks,

**Comment by FrEaKmAn** [comment]
I think this is normal

1. Extra colon is how legend is built. You can check the code here https://github.com/danvk/dygraphs/blob/ecf84f57447c011a140d36ba5181e41dbb93f121/src/plugins/legend.js#L259
2. For the time, again dygraph tries to remove zeros in time https://github.com/danvk/dygraphs/blob/ecf84f57447c011a140d36ba5181e41dbb93f121/src/dygraph-utils.js#L376

if you want to solve this, you need to have custom legend and custom dateformatter...

**Comment by danvk** [comment]
@FrEaKmAn is right, this is the expected behavior. You can customize it using a `valueFormatter`.
