### ISSUE TITLE
feature request: save as image/file

### ISSUE THREAD

**Issue by butterflyx** [danvk/dygraphs#642]
I just started using Dygraphs due to the Yii2 widget from Sibilino (https://github.com/Sibilino/yii2-dygraphswidget) an like it already.

But I'm missing an important feature: the possibility to save the rendered graph as image or file e.g. pdf. 

Using the browser printing functionality is not an option, as one use case would be to save the plots to the filesystem and reference them in a database as history. 

It would be great if such a feature could be implemented. Thank you! :)

**Comment by rochejul** [comment]
Hi,

You can easily have this feature using html2canvas (because the legend is HTML dom elements). After that, you can serialize the canvas to an image.

If needed, use with html2canvas the project "blueimp-canvas-to-blob" to have have a blob object and to save it

Cheers

**Comment by danvk** [comment]
There's been extensive discussion of this elsewhere:

- http://cavorite.com/labs/js/dygraphs-export/
- https://groups.google.com/forum/#!topic/dygraphs-users/whcMjtBE7s0
- http://stackoverflow.com/questions/11532219/save-dygraph-chart-into-jpg-image-on-my-local-hard-drive
