### ISSUE TITLE
Resize and timing issue will cause exception

### ISSUE THREAD

**Issue by timeu** [danvk/dygraphs#647]
Problem:
====
There seems to be a timing issue, when a Dygraphs chart is created using a URL as a datasource and when calling `dygraph.resize()` too early. 

The problem is that when no `xAxis_` options is spcified for the `DygraphOptions`, it will be set to an empty dictionary (https://github.com/danvk/dygraphs/blob/master/src/dygraph-options.js#L63)

Only when the options are reparsed (which happens when options are either updated or data is made available) in the `DygraphOptions.prototype.reparseSeries` function (https://github.com/danvk/dygraphs/blob/master/src/dygraph-options.js#L135), the `xAxis_` property is set to ` { options : {} };`

That means when you call `resize()` on the dygraph before the data is returned by the XHR request, the `DygraphOptions.prototype.getForAxis` will throw at line https://github.com/danvk/dygraphs/blob/master/src/dygraph-options.js#L244 because `var axisOptions = userAxis.options;` will be `undefined`. 

Workaround: 
===
Delay the call to `resize` until the XHR request for the datasource returns. 

Solution:
===
Either instantiate the `xAxis_` propert as dict containing a  sub-property `options` or check for undefined in the `DygraphOptions.prototype.getForAxis` function.

I can create a pull-request.

**Comment by danvk** [comment]
Is the issue that _you're_ calling `g.resize()` or that the user is resizing the window? I'd avoid calling any methods on a dygraph with remote data until `g.ready()` fires.

**Comment by timeu** [comment]
Yeah it's actually because I am calling `g.resize()` (this is necassary because for the `GWT` wrapper `Dygraph` is instantiated in the constructor and afterwards attached to the DOM --> requires to `resize` in order to properly draw the chart). 

I didn't know about the `g.ready()` callback. 
I am now calling `resize` in the `ready` callback and can confirm that this fixes the issue. 

Sorry for the invalid bug report.

**Comment by danvk** [comment]
I wonder if the same thing would happen if you resize the window before the XHR comes back. There may be a bug lurking in there still.
