### ISSUE TITLE
rollPeriod shows more data than expected

### ISSUE THREAD

**Issue by abdrabo** [danvk/dygraphs#649]
rollPeriod in the following example shows points that doesn't exist. This is very confusing since I am trying to compare today's data which is not complete yet with yesterday and the graph has points in the future.
```javascript
g = new Dygraph(document.getElementById("graph"), [
    [0, 5, 4],
    [1, 9, 8],
    [2, 4, 3],
    [3, 3, 2],
    [4, 8, null],
    [5, 7, null],
    [6, 2, null],
    [7, 9, null]
], {
    rollPeriod: 4
});
```
Example in JSFiddle: http://jsfiddle.net/eM2Mg/6755/

I am willing to solve this problem but I am not sure which option is better?
Option 1: ignore the last continuous points with null values
Option 2: ignore any point with null value

**Comment by danvk** [comment]
The behavior is correct. dygraphs averages the last N points, whatever they
are. If you want different behavior, you need to "roll" the data yourself.
I'm open to suggestions on making custom rollers let of the API.

**Comment by abdrabo** [comment]
I wrote my own roll today but I can not understand how is the current behavior correct! The current implementation shows point in the future.
