### ISSUE TITLE
 Legend for numeric x-axis

### ISSUE THREAD

**Issue by Onimo** [danvk/dygraphs#652]
Like in this example:
http://dygraphs.com/tests/csv-numeric-x.html

 Is not possible to show this:  X:3 : Y:0 (legend field) but only this: 3: Y: 0

It is planned to place this option (X legend)?

**Comment by kbaggott** [comment]
Have a look at this maybe? http://dygraphs.com/tests/value-axis-formatters.html

**Comment by cisenor1** [comment]
Has any progress been made on this?

**Comment by Onimo** [comment]
Until now, no.
I am waiting for an update. Or some fantastic idea.
As simple as this:

X:3 : Y:0

**Comment by kbaggott** [comment]
If I understand you right, I think your answer is to use the valueFormatter function, take a look at this.
http://jsfiddle.net/NtBPk/633/ 
Obviously this example has dates but it would be the same for a numeric x-axis.

**Comment by cisenor1** [comment]
Damn, that's nice. I hope you don't mind that I'm now going to refer to dates as "Banana Gerbils"

**Comment by danvk** [comment]
In addition to `valueFormatter`, there's also a [`legendFormatter`](https://github.com/danvk/dygraphs/pull/683) option which gives you a bit more control. (You'll need to build dygraphs from `HEAD` to get it—it hasn't been released yet.)
