### ISSUE TITLE
Fractional second handling (millisecond time)

### ISSUE THREAD

**Issue by kuna-matata** [danvk/dygraphs#654]
The following three threads discuss handling millisecond time. I got the data to display with R library(dygraphs), but dygraphs.js appears to truncate or round the data to the nearest second. Please consider adding support (or describe how) to resolve fractional seconds.

- https://github.com/danielkrizian/rChartsDygraphs/issues/7
- http://stackoverflow.com/questions/31299871/dygraph-millisecond-plotting
- https://github.com/rstudio/dygraphs/issues/46

**Comment by TonyDIRL** [comment]
This would be something I'd also be very interested to have answered.

**Comment by danvk** [comment]
Here's a repro: http://jsfiddle.net/eM2Mg/7082/

The chart is _displayed_ fine, you just lose the milliseconds in the axis labels and legend.

**Comment by kuna-matata** [comment]
Interesting that danvk's example works. My experience was that it would essentially ignore the fractional seconds and collapse all abscissa values to 12:34:57. I will try to work on replicating the issue. I'm using it through R Shiny dygraphs interface package, so perhaps the error originates there.

**Comment by TonyDIRL** [comment]
Thanks for the response @danvk .
I attempted to get this display working in dygraphs quite a while ago but I could never figure out the correct configuration of axisLabelFormatter and valueFormatter.
http://jsfiddle.net/kaliatech/DfWNz/3/

Could you please suggest a workaround that would display milli's in the axis label and legend?

**Comment by Haycen** [comment]
Have anyone figured out how to force dygraphs to not truncate or round the data to seconds and display milliseconds?

**Comment by TonyDIRL** [comment]
Unfortunately I could never get this working. The plotly or highcharter packages handle subsecond plotting much better

**Comment by statquant** [comment]
It is really too bad dygraph is so much better at downsampling than plotly, but non-fractional second is just a no go for anyone in the finance field :(

**Comment by danvk** [comment]
Closed by #774
