### ISSUE TITLE
Synchronization is unusably slow

### ISSUE THREAD

**Issue by jonathanapp** [danvk/dygraphs#658]
The synchronizer demo gives the false impression this feature is usable; for a couple thousand points and a handful of linked charts, it can take 30 seconds to a minute for the page to load.

See details here:

https://groups.google.com/forum/#!topic/dygraphs-users/OxFcMuCz-gk

**Comment by danvk** [comment]
Can you point to an example?

Let's try to keep the tone positive. This is a volunteer-based open source project.

**Comment by jonathanapp** [comment]
Sorry if my tone was too negative!

Here's a version of NoisyData() with 5k points:

http://pastebin.com/RKntKv3Q

Loading dygraphs-master/tests/synchronize.html in Chrome will then take about 30 seconds.
Note that with only 2k points, it takes about 6 seconds. So the synchronization is not scaling well.

(Without sync on, it takes about 4 seconds).

Given the importance (for my project) I'd happily help fix the issue; should I begin in synchronizer.js?

**Comment by danvk** [comment]
Is it the loading or the interactions that are slow? On every frame, `synchronizer.js` [calls getRowForX][1], which is O(n log n), so it is expected to be super-linear.

It's possible there's some kind of O(n^2) thing going on in the initialization. Can you try checking how often the charts are redrawn? You could add a `console.log` in `drawGraph` or one of the plotters, for instance.

[1]: https://github.com/danvk/dygraphs/blob/24f982449792c7ba2a56af0e1e428a0896702080/src/extras/synchronizer.js#L194

**Comment by jonathanapp** [comment]
Loading is slow, interactions are snappy. Even with 12 plots and thousands of points, the zoom/pan interaction is acceptable (slower obviously, but acceptable) but the initialization takes a full minute.

I'll investigate chart redraws.

**Comment by jonathanapp** [comment]
I profiled the `dygraphs-master/tests/synchronize.html` in Chrome Canary (new to those dev tools). It turns out the error bars were taking up the lion's share of time; I added a "return;" at the top of `_errorPlotter()` and it sped it up from 30 seconds to just a few seconds.

For my **actual** use case, I don't have any error bars. But I did turn off `_fillPlotter()` and got my page load time down to 10 seconds. Not ideal, but good enough for now.

Below is a screenshot from profiling my page. You can see at around 3500ms begins 4 distince "clumps" that each take about 1500ms...I believe each "clump" is for a single chart in my page (I have 12 charts that are synchronized).

As you can see the `attachZoomHandlers/attachSelectionHandlers` take up the bulk of the time. I'm not familiar enough with the code to know what to do next, so I'm going to stop at turning off fill for now and revisit if/when users complain.

Profiler:
http://i.imgur.com/CrpVgo9.png

![profile](https://cloud.githubusercontent.com/assets/13562081/9913394/abb6ee5a-5c7a-11e5-9c97-4a3d3c6c4f6b.png)

**Comment by danvk** [comment]
Which version of dygraphs are you using? There were [significant speedups][1] for `fillGraph` in the 1.1.1 release.

[1]: https://github.com/danvk/dygraphs/pull/462

**Comment by jonathanapp** [comment]
`dygraphs-master\src\dygraph-combined-dev.js`

**Comment by danvk** [comment]
You should definitely be using the non-development version of dygraphs if performance is a concern. Either build it yourself or see http://dygraphs.com/download.html

**Comment by jonathanapp** [comment]
No difference in load time for me. I might revisit later; my guess is, it shouldn't be doing all that rendering while attaching the handlers, it should only render at the end (for synced charts). But it'll take a while to investigate.

**Comment by danvk** [comment]
There is an optional second parameter to [`updateOptions`][1] which blocks redraws. You might try setting that in the relevant places in `attachZoomHandlers`/`attachSelectionHandlers` and see if it makes  a difference.

[1]: http://dygraphs.com/jsdoc/symbols/Dygraph.html#updateOptions

**Comment by jonathanapp** [comment]
That's it!

Change line 173 of synchronizer.js from
`}, false /* no need to redraw */);`

to

`}, true /* no need to redraw */);`

And it's now lightning fast. 2.5 seconds vs 20 seconds.
**true** blocks redraw, not **false**.

Thanks a lot for your help!

**Comment by danvk** [comment]
Ha! I'm glad this turned out to be so trivial.

I put out a PR to fix this. I don't see any reason why the `updateOptions` in `attachSelectionHandlesr` wouldn't block redraws, too.
