### ISSUE TITLE
Logscale gets buggy when x values starts from 0

### ISSUE THREAD

**Issue by reinert** [danvk/dygraphs#663]
I hadn't time to build an example, but I have to register it.

I tested plotting timeseries with both axes in logscale. When my x values starts with exact zero, the graph isn't built properly. Then when I switch my initial x values to `0.00000001` the graph is correctly built.

**Comment by danvk** [comment]
It's breaking because `log(0) = -Infinity`. I'm not what you'd expect dygraphs to do here.

**Comment by reinert** [comment]
You're right. It's a problem of my domain (which is working with deltas), not dygraphs'.
