### ISSUE TITLE
Support metric prefixes instead of scientific notation

### ISSUE THREAD

**Issue by alecbenzer** [danvk/dygraphs#666]
Eg, add the option to display the value 2^30 as 1.07G instead of 1.07e+9. Even better if you can add an optional additional suffix, so that with suffix='B', we'd get 1.07GB.

https://en.wikipedia.org/wiki/Metric_prefix

**Comment by danvk** [comment]
Are these what you're asking for?
http://dygraphs.com/options.html#labelsKMB
http://dygraphs.com/options.html#labelsKMG2

**Comment by alecbenzer** [comment]
Yes! I'd looked for something similar a while back but couldn't find it. The 'B' suffix might be nice but isn't a big deal.
