### ISSUE TITLE
Error: axis 0 of graph at [Dygraph ] can't be displayed in log scale for range

### ISSUE THREAD

**Issue by vdtidake** [danvk/dygraphs#667]
When I try to set valueRange as [1,100] for y axis for logarithmic scale, I am getting this error
```javascript
axis 0 of graph at [Dygraph ov-chart-1] can't be displayed in log scale for range [-100 - 200]

console.error('axis ' + i + ' of graph at ' + axis.g +
```

Is it allowed to have valueRange when logarithmic scale is set to true?

**Comment by danvk** [comment]
Can you share an example via dygraphs.com/fiddle?
