### ISSUE TITLE
points not being connected

### ISSUE THREAD

**Issue by RussNelson** [danvk/dygraphs#668]
http://rths.us/daterange-test.html shows a very simple test of a four-column csv graph that doesn't display correctly. I have four data series with just two points in each series. I expect to see  four horizontal lines, but I only see two (Chromium or Firefox on Linux and Chrome on Android and Firefox on Windows 8). dygraph-combined.js is version 1.1.1. If I sort the lines by date, I only get one line. If I sort the lines by column (17, 82, 83, 9), I get no lines.

Date,r17,r82,r83,r9
2013-10-17T21:00:00Z,,,,9
2014-05-29T18:00:00Z,,,,9
2013-10-17T21:00:00Z,17,,,
2014-05-29T17:00:00Z,17,,,
2014-05-29T18:00:00Z,,82,,
2014-05-29T18:00:00Z,,,83,
2014-10-11T04:00:00Z,,,83,
2015-05-22T04:00:00Z,,82,,

**Comment by danvk** [comment]
You need to sort your data. I'm quite surprised that you don't get a warning about that.

Can you share an example of what it looks like if you sort the dates? (maybe via dygraphs.com/fiddle).

**Comment by RussNelson** [comment]
Nope, don't get a warning. If I sort the dates, I get just one line (17). The other data series are rendered as points unconnected by a line.

**Comment by danvk** [comment]
OK, I see what's going on. dygraphs is behaving as expected.

First of all, don't pass unsorted data to dygraphs. It should just sort it for you, so it only confuses the issue.

When your data is sorted, you'll have a few series (e.g. `r9`) where the points are separated by null values. To dygraphs, this means that there's a gap and it will be rendered as such. If you want to draw across the gap, you'll need to use the [`connectSeparatedPoints`][1] option. See [these][2] [two][3] examples.

[1]: http://dygraphs.com/options.html#connectSeparatedPoints
[2]: http://dygraphs.com/tests/connect-separated.html
[3]: http://dygraphs.com/tests/independent-series.html

**Comment by RussNelson** [comment]
AHA! Yes, indeed, when I fill in the nulls by connecting them, it graphs them as connected lines. Or your solution works with a sorted version of the data set from above. Thanks so much.

**Comment by RussNelson** [comment]
Now we go on to see if dygraphs can handle 90 series. :-)
