### ISSUE TITLE
errorBars causing graph not to render

### ISSUE THREAD

**Issue by cbranje** [danvk/dygraphs#671]
When I comment out errorBars: true the graph appears, with the error values as another series. If I take out the comment and put the statement in, the graph does not render. The the outline, no lines and no annotations. 

	  	var data = [];

	    data.push([new Date("2007/01/01"),10000,1]);
		data.push([new Date("2007/01/02"),9463.777815,16]);
		data.push([new Date("2007/01/03"),8748.659709,31]);
		data.push([new Date("2007/01/04"),7779.545394,46]);
		data.push([new Date("2007/01/05"),6846.280611,61]);
		data.push([new Date("2007/01/06"),6042.265704,76]);
		data.push([new Date("2007/01/07"),5052.064845,91]);
		data.push([new Date("2007/01/08"),4089.830899,106]);
		data.push([new Date("2007/01/09"),3195.631158,121]);
		data.push([new Date("2007/01/10"),2541.901849,136]);
		data.push([new Date("2007/01/11"),1805.774559,151]);
		data.push([new Date("2007/01/12"),1167.31813,166]);
		data.push([new Date("2007/01/13"),433.566787,181]);
		data.push([new Date("2007/01/14"),-475.4670651,196]);
		data.push([new Date("2007/01/15"),-1171.779711,211]);
		data.push([new Date("2007/01/16"),5000,226]);
		data.push([new Date("2007/01/17"),4091.462451,241]);
		data.push([new Date("2007/01/18"),3386.055666,256]);
		data.push([new Date("2007/01/19"),2728.37301,271]);
		data.push([new Date("2007/01/20"),2167.424525,286]);
		data.push([new Date("2007/01/21"),1483.230149,301]);
		data.push([new Date("2007/01/22"),917.4477079,316]);
		data.push([new Date("2007/01/23"),179.2235937,331]);
		data.push([new Date("2007-01-24"),-625.1312787,346]);
		data.push([new Date("2007/01/25"),-1209.343528,361]);
		data.push([new Date("2007/01/26"),-1832.497902,376]);
		data.push([new Date("2007/01/27"),-2426.93031,391]);
		data.push([new Date("2007/01/28"),-2940.290957,406]);
		data.push([new Date("2007/01/29"),-3745.675041,421]);
		data.push([new Date("2007/01/30"),-4412.335834,436]);
		data.push([new Date("2007/01/31"),-5303.819068,451]);
		g = new Dygraph(document.getElementById("graphdiv"), data,
		{			
			labels: [ "Date", "Series1" ],
			//errorBars: true,
			axisLineColor: "red",
			fillAlpha: 0,
			sigma: 2.0
			/*underlayCallback: function(canvas, area, g) {
                // Selecting a date in the middle of the graph. 
                var splitDate = new Date("2006-11-19").getTime();
                var coords = g.toDomCoords(splitDate, 2.25);

                // splitX and splitY are the coordinates on the canvas for (2006-11-19, 2.25).
                var splitX = coords[0];
                var splitY = coords[1];

                // The drawing area doesn't start at (0, 0), it starts at (area.x, area.y).
                // That's why we subtract them from splitX and splitY. This gives us the
                // actual distance from the upper-left hand corder of the graph itself.
                var leftSideWidth = splitX - area.x;
                var rightSideWidth = area.w - leftSideWidth;
                var topHeight = splitY - area.y;
                var bottomHeight = area.h - topHeight;
     
                // Bottom section: y = (-Infinity, 2.25)
                canvas.fillStyle = 'pink';
                canvas.fillRect(area.x, splitY, area.w, bottomHeight);
              }*/
			
		}	
  );

**Comment by danvk** [comment]
I believe the format needs to be:

    [new Date("2007/01/01"),[10000,1]]

not

    [new Date("2007/01/01"),10000,1]

see http://dygraphs.com/data.html#array
