### ISSUE TITLE
snapshot releases

### ISSUE THREAD

**Issue by reinert** [danvk/dygraphs#672]
I need to use the current repository version, but it seems this project doesn't release snapshot versions. It really would be useful to apply a more often release cycle. Like https://github.com/angular/bower-angular/releases .

**Comment by danvk** [comment]
It's not a bad idea. Once I complete #453 and #508, I'd like to do a 2.0.0 release.

**Comment by Ventajou** [comment]
This issue is 10 months old, any idea when a new release will be available on npm? It only takes minutes to publish...

**Comment by danvk** [comment]
@Ventajou try `npm install`ing the 2.0.0-dev1 branch. https://github.com/danvk/dygraphs/tree/2.0.0-dev1

If you're interested in helping maintain dygraphs, please let me know #727

**Comment by danvk** [comment]
There have been several releases (on npm) since this issue was filed. This is fixed.
