### ISSUE TITLE
xAxis zooming is broken when using dateWindow of Date

### ISSUE THREAD

**Issue by ctron** [danvk/dygraphs#685]
Setting a `dateWindow` in the options of type `Date`, will break the zoom X axis functionality.

**Comment by danvk** [comment]
This behavior is exactly what you'd expect http://dygraphs.com/options.html#dateWindow

> Initially zoom in on a section of the graph. Is of the form [earliest, latest], where earliest/latest are milliseconds since epoch. If the data for the x-axis is numeric, the values in dateWindow must also be numbers.

**Comment by ctron** [comment]
And if the data for the x-axis is not numeric?

**Comment by danvk** [comment]
> Is of the form [earliest, latest], where earliest/latest are milliseconds since epoch.
