### ISSUE TITLE
Bug: Asynchronous Series Loading with multiple axes

### ISSUE THREAD

**Issue by musicist288** [danvk/dygraphs#689]
This issue pertains to using dygraphs in an API driven application. At load time I have a bit of metadata that instructs the client-side application of which data series to load. At run-time, the application asynchronously loads all of the series metadata and data sets for those series, merged the data into a 2d array and updates the graph with the new data and settings. The issue I'm encountering can be seen in this fiddle:

http://jsfiddle.net/3p3ko24p/

Note that the chart renders with two different data sets at different times (simulated here by a `setTimeout`).  In my application, this results from asynchronously loading and updating. I'd rather not wait until all of the data is available to draw the chart; progressive rendering makes users happier than staring at a loading icons, or so it seems. 

I don't know if this is a case that if the library wants to handle or not but I appreciate any thoughts or feedback.

**Comment by danvk** [comment]
Looks like you're running into #629. I'll close this as a dupe. A workaround is to make sure your chart has two y-axes from the get-go.

**Comment by musicist288** [comment]
Ok. Thanks.
