### ISSUE TITLE
Hide series value and name from Legend.

### ISSUE THREAD

**Issue by ThePlastic** [danvk/dygraphs#698]
Could you please add an option that allows to select which series show on legend?

**Comment by danvk** [comment]
This (and much more) can be done with the new `legendFormatter` option; see #683.

**Comment by ThePlastic** [comment]
I tried what you suggest ([#683](https://github.com/danvk/dygraphs/pull/683) but I wasn't able to make that work. Is the "legend" plugin needed? In your example you use "digraphs.js", i always used "digraphs-combined.js" is that the reason it doesn't work for me?
