### ISSUE TITLE
RangeSelector - is disablind series after slide

### ISSUE THREAD

**Issue by snuuve** [danvk/dygraphs#702]
When i set range of RangeSelector everythink is ok.

![2](https://cloud.githubusercontent.com/assets/9519759/11627418/5811ab68-9cea-11e5-866f-50d7efa0f3b8.png)

But when i try to move RangeSelector , my series dissapear.

![3](https://cloud.githubusercontent.com/assets/9519759/11627426/67939858-9cea-11e5-8434-031eb5a620b7.png)

No problem when i dragging graph. Only RangeSelector.

Is it problem of uisng double Y axes  (y1,y2)?
What is wrong?

**Comment by danvk** [comment]
please provide a repro, preferably via dygraphs.com/fiddle

**Comment by snuuve** [comment]
Same problem with interactions.js. On 'double click' i have graph.resetZoom() and on 'mouse wheel' i have zoom. When i dblclick resetZoom is working but then when i zoom in/out my series disapear.
