### ISSUE TITLE
Is Release 2.0 in near future, can we have some tentative dates ?

### ISSUE THREAD

**Issue by mrin9** [danvk/dygraphs#705]
planing to upgrade our app, and the dygrpaphs current version is way behind than whats in github. Do you have any plans to release it anytime soon? I

**Comment by danvk** [comment]
No, you can't! dygraphs is entirely volunteer-driven and releases are done on a best-effort basis. If you'd like to get involved with the project and help make a release happen, it would be appreciated!

**Comment by mrin9** [comment]
sure I would like to, If you have some task in mind can you put it them at some place. I can help in testing documenting etc. I do want to sync latest github commit with the version thats downloadable from the website . These are more than a year apart and IMO thats a big gap in javascript world

**Comment by kbaggott** [comment]
This conversation seems to have an answer, @mrin9 if you are interested have a look at #727, but closing this now.
