### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ktsaou** [danvk/dygraphs#706]
I would like to let you know I use dygraphs with [netdata](https://github.com/firehol/netdata/).

You can find a live demo of it at [netdata.firehol.org](http://netdata.firehol.org/).

Dygraphs outperform anything I tried. It made netdata UI speedy and responsive (compare it with google charts - there is a link to the old dashboard at the top right of the screen).

Dygraphs are packed with features, I use them to synchronize hundreds of charts, create huge detailed charts but also sparklines.

Excellent work!
Thanks!

Costa Tsaousis

**Comment by danvk** [comment]
Glad it worked for you! If you'd like to be added to the list of users (`users.html`), feel free to send a PR.

**Comment by ktsaou** [comment]
I tried to send you an mail to the address found at the bottom of users.html, but I got a non-delivery report.

**Comment by danvk** [comment]
yeah, send a PR instead.
