### ISSUE TITLE
XMLHttpRequest, CORS, and Google Sheets

### ISSUE THREAD

**Issue by adavidzh** [danvk/dygraphs#707]
This is not necessarily a bug, but because of [the way dygraphs performs the requests](https://github.com/danvk/dygraphs/blob/dd74404fac69f23183ff8e540a018ca35bab4f7a/src/dygraph.js#L3155-L3156), getting CSV data from Google Sheets was not working out of the box because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS).
Here's a snippet from how I worked around this using `tabletop.js`:
```javascript
var key = "(a google sheet key)";

$(document).ready(function() {

  Tabletop.init({
    key: key,
    callback: fillItUp,
    simpleSheet: true,
  });

});

function fillItUp(data, tabletop) {
  csv = tabletop.sheets("Sheet1").toArray();
  vals = [];
  for (i in csv) {
    row = csv[i];
    vals.push(
      [parseInt(row[0]) * 1000, parseInt(row[1]), row[2]]
    );
  }
```
after which `vals` can be used to create the `Dygraph`.

**Comment by danvk** [comment]
I would not call this a bug in dygraphs. I've somewhat deliberately kept the XHR feature of dygraphs simple because I'd prefer that it stay focused on charting data, rather than loading it or processing it. The munging you've done in your callback is a perfectly reasonable approach.

**Comment by adavidzh** [comment]
No claim of a bug... Moving on.
