### ISSUE TITLE
Can't render graph inside hidden div

### ISSUE THREAD

**Issue by justin-hackin** [danvk/dygraphs#709]
Reopening -> https://github.com/danvk/dygraphs/issues/631 

I think this is still an issue. See my slight modification of the fiddle from the linked issue here: http://jsfiddle.net/7dq1LLg3/.  Click on Tab 3, where the graph was moved.    When you render a graph in a hidden div it does not display correctly.

As I workaround, I may have to create an offscreen div  and then append it to the hidden div but it would be awesome if I didn't have to....

**Comment by toni07** [comment]
Hi Justin, in the fiddle you have two tabs with the same id: "tabs-3".

**Comment by kbaggott** [comment]
I think toni07 is correct if you change the id on your tabs it works http://jsfiddle.net/7dq1LLg3/1/ I can see a slight glitch when the chart first loads but this could probably be taken care of with a setTimeout for 50ms or so on the tab change just to let the div get its height.

**Comment by kbaggott** [comment]
I have tested the fix mentioned above and without any more replies I'm closing this issue.

**Comment by AlexeyRomanchenko** [comment]
Each graph has resize() method, so you can catch event, when your tab become active and just call myGraph.resize()
It should help
