### ISSUE TITLE
Slowness in special cases

### ISSUE THREAD

**Issue by tyduptyler13** [danvk/dygraphs#731]
Hello,

I created a powerful display library using your library for my work. Everything works great except on a few select computers. Some machines experience extreme slowdown when they move their mouse around. It seems to be worse when they leave the graph area but I haven't been able to narrow it down very much as I am not in possession of any machine that reproduces the results.

Thus far the two machines that I have managed to get this to happen on were:
- A high end mac book pro
- A mid tier lenovo running fedora

The issue happened in chrome which is the primary browser I support, I altered my code to support firefox as well but firefox just naturally runs slowly.

I believe the issue is tied to the mouse move handler, but it is possible I am wrong.

I am sorry I can't be much more specific, I honestly have been puzzled by this one for a month or two.

Here is a [link](http://bgpmon-stats.netsec.colostate.edu/) to the public site that has the issue. Just scroll down to the graph, move the mouse around and if the graph gitters with the browser locking up for a second or two then your computer also has the issue. Unfortunately, I only found my bosses (of course) computer and an old coworkers to have the issue so I know its rare.

Any help would be appreciated.

**Comment by timeu** [comment]
Is it possible to record a timeline profile (JS profiler) in Chrome Dev Tools on the machine that is showing the performance problems ? You can post it here and one can have look to see what is causing the delay. Also try to run the site in Incognito mode in Chrome to make sure that no 3rd party plugins are causing the issue.

**Comment by tyduptyler13** [comment]
I will see what I can do. I'll have to get my hands on my bosses computer for awhile.

**Comment by hampusohlsson** [comment]
@tyduptyler13 you can try and see if those Chrome installations has disabled Hardware Acceleration (Chrome menu > Settings > Show advanced settings > Scroll down to "System" > Check "Use hardware acceleration)... that might be what's causing the slow performance on some computers

**Comment by tyduptyler13** [comment]
I don't work at that company anymore and barely recall what the problem was. I am going to close this as its not very specific and very unlikely to be reproduced.
