### ISSUE TITLE
Provide TypeScript definitions

### ISSUE THREAD

**Issue by danvk** [danvk/dygraphs#735]
There should be TypeScript declarations for dygraphs in [DefinitelyTyped][1]. This will help catch typos & type errors in the options object and method calls.

[1]: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by kevmal** [comment]
Perhaps a starting point
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7404

Not sure if @DenisKolodin is still pursuing this?

**Comment by DenisKolodin** [comment]
I haven't finished it, because switched to Elm, but you can take it without any restrictions.

**Comment by danvk** [comment]
Here's a script I wrote to help with this.
https://gist.github.com/danvk/c3aec8b565de88347e5a760195fe6468

PR is out for DefinitelyTyped.

**Comment by danvk** [comment]
These are now available:

```
$ typings search dygraphs
Viewing 1 of 1

NAME     SOURCE HOMEPAGE            DESCRIPTION VERSIONS UPDATED
dygraphs dt     http://dygraphs.com             1        2016-09-24T17:37:33.000Z
```

**Comment by matzefriedrich** [comment]
What about typings for version 2.0.0?

**Comment by danvk** [comment]
Haven't gotten around to it yet. A third party contribution would be very
welcome here.
