### ISSUE TITLE
Graphs not rendering when in background tab

### ISSUE THREAD

**Issue by cesarvarela** [danvk/dygraphs#737]
Latest Chrome seems to have this issue. We have a collection of graphs that auto-refresh over time, but when we leave the page in a background tab, and get back to it after a couple of supposed redraws, the graphs appear blank.

Did anyone el se had this issue?

**Comment by pshevtsov** [comment]
Hello @cesarvarela !
Thanks for reporting this. Could you please provide us with the URL to the page (or jsFiddle) where such behaviour could be reproduced?

Thanks!

**Comment by daraosn** [comment]
I experienced the same issue with latest Chrome...

To reproduce, using Chrome:
1) Tab #1: Go here: http://dygraphs.com/gallery/#g/dynamic-update
2) Tab #2: open an empty tab
3) Wait until Tab #1 loads
4) Switch to Tab #2 and wait at least 1 second
5) Go back to Tab #1, after less than a second the chart lines disappear

A way I'm working it around (using jQuery):
```
$(window).on('visibilitychange', function(e) {
  myDygraph.resize(1,1);
  myDygraph.resize(myDygraph.width_,myDygraph.height_);
});
```
Where `myDygraph` is your dygraph object.

**Comment by daraosn** [comment]
@cesarvarela so no proper solutions for this?

**Comment by danvk** [comment]
This is discussed here:
http://stackoverflow.com/questions/22260579/resizing-tabbed-dygraph-window
