### ISSUE TITLE
Difference in behaviour of dygraph-combined.js & dygraph-combined-dev.js

### ISSUE THREAD

**Issue by mrankur88** [danvk/dygraphs#740]
I am moving from dygraph 1.0.1 to dygraph 1.1.1.

I had been using my own custom option in dygraph.

When I link my application to the expanded version of 1.1.1, I get an exception "Uncaught invalid option" as expected in the new version. But when I link my application to the minified version of 1.1.1, I do not get this exception.

**Comment by danvk** [comment]
Congratulations, you've discovered the difference between these two files!

You should develop using the `dygraph-combined-dev.js` version of dygraphs. This will give you noisier, clearer error messages. Once your chart is working and you'd like to distribute it to clients, you can switch to `dygraph-combined.js`, which doesn't check the validity of options. This is both a performance and a space optimization.
