### ISSUE TITLE
Working on an existing company project which has DyGraph Liner chart. In 'Semi Log' chart, when i'm trying to zooming in on Y-Axis by Drag the mouse on some part, it will give me totally different output. What should change so that i can fix the bug.

### ISSUE THREAD

**Issue by ParthGondaliya** [danvk/dygraphs#744]
Filing a bug report? Please include the following:

1. Link to a page which demonstrates the problem, preferably a jsfiddle (use http://dygraphs.com/fiddle as a template)
2. Browser and Operating System that exhibit the problem
3. Version of dygraphs that you're using

It also helps if you include the non-compacted version of the JS on your
page. For instance, instead of doing this:

```html
<script type="text/javascript" src="dygraph-combined.js"></script>
```

do this:

```html
<script type="text/javascript" src="dygraph-combined.dev.js"></script>
```

This makes error messages and debugging simpler. The jsfiddle does this automatically.

**Comment by danvk** [comment]
There's not enough information here to reproduce the issue.
