### ISSUE TITLE
Real-time streaming plot?

### ISSUE THREAD

**Issue by haisamido** [danvk/dygraphs#749]
Can dygraphs perform real-time streaming plots, i.e. not a plot of a file, or a pre-defined array of data, but a stream set of data points?

**Comment by pshevtsov** [comment]
Hello, @haisamido!

Thanks for your interest in Dygraphs library. Check this demo for dynamic update — http://dygraphs.com/gallery/#g/dynamic-update

Hope this helps.

**Comment by scheung38** [comment]
But plotting stops as soon as one zooms in....

**Comment by danvk** [comment]
You could explicitly set `dateWindow` to change that behavior.

**Comment by scheung38** [comment]
dateWindow when set to true, doesn't do anything?

**Comment by danvk** [comment]
http://dygraphs.com/options.html#dateWindow

**Comment by haisamido** [comment]
I have streaming CSV data coming in, which I want to plot as the data comes in? I am not sure how leverage the example given in http://dygraphs.com/gallery/#g/dynamic-update
