### ISSUE TITLE
[ "clear" problem] When changing YAxis from 1 to 2 by using updateOptions.

### ISSUE THREAD

**Issue by flexdeviser** [danvk/dygraphs#751]
first I created a single yAxis graph, after that I update the options to two yAxis, then I got this graph.
![image](https://cloud.githubusercontent.com/assets/3424332/15733254/794c69ee-28c7-11e6-929e-3830a0138a2f.png)
The right side of graph has something wrong. so I think, you need to clear the canvas before drawing 'y2' axis.
btw, I just add "this.plotter_.clear();" into "Dygraph.prototype.updateOptions", and the problem fixed.

**Comment by jpardey** [comment]
Thanks for posting this. I've been having the same problem, and your fix solved it for me.

For my own usage, I've added the `this.plotter_.clear()` call into the `if (!block_redraw)` block within the `if (file)` block of that function. Is there a better place to include it? I doubt this will be an issue for my work, but I could imagine it still being a mess if I was changing axis settings without updating the files options, and I have no idea how it will work with annotations.

**Comment by flexdeviser** [comment]
@jpardey I'm so glad your problem solved. But I think "this.plotter_.clear()" is just a temporary solution. I expect there will be a good way or some guy to solve this problem.

**Comment by danvk** [comment]
Saem as #629
