### ISSUE TITLE
Dygraphs for R Version 1.1.1.0 - not working with shinydashboard package

### ISSUE THREAD

**Issue by sohomdatta** [danvk/dygraphs#765]
I am using dygraphs for a R Shiny +shinydashboard project. 
**OS: Win 7 Enterprise 64 bit
R version: 3.2.3 64-bit/32-bit 
Package:
shiny version: 0.13.2
shinydashboard version: 0.5.1
htmlwidgets version: 0.7**
I have around 15-20 different dygraph time series plots in my shiny dashboard.
Worked without issues with dygraphs version 0.9.
After updating to dygraphs 1.1.1.0,  the following stopped working:
shinydashboard::valueBox - stopped rendering
dygraphs - random behaviour - not fitting inside the windows, partially rendered.

Reverting back to dygraphs version 0.9, shinydashboard functionalities are normalized again.

**Comment by danvk** [comment]
This sounds like more of a shiny / R issue. You'll have better luck asking them.
