### ISSUE TITLE
Rolling average filter is not centered which causes additional delay

### ISSUE THREAD

**Issue by taismi** [danvk/dygraphs#772]
Dygraphs calculates rolling average for data point d(k) as
[ d(k)+d(k-1)+d(k-2)+...+d(k-n) ] / [n+1]
Only previous values are used. This causes delay of n data poins. Center of the peaks does not match. I consider this as a bug.

![dygrapsh_rolling_average](https://cloud.githubusercontent.com/assets/16210105/18034393/8cd83ab2-6d44-11e6-870b-3041adc01302.png)
http://jsfiddle.net/pmpLmqpf/

Better average would be this. Delay is n/2 and center of the peaks are matched.
[ d(k-n/2)+...+d(k-2)+d(k-1)+d(k)+d(k+1)+d(k+2)+...+d(k+n/2) ] / [n+1] when n+1 is odd.

If n+1 is even there is an additional delay of 1 but thats much better than the original way of calculating the average.
[ d(k-n/2)+...+d(k-2)+d(k-1)+d(k)+d(k+1)+d(k+2)+...+d(k+(n/2)-1) ] / [n+1] when n+1 is even.

**Comment by danvk** [comment]
This is working as intended. It's very explicitly a trailing average. For your application, keeping the center of the peak constant is important. For other applications, not incorporating data from the future might be equally important.

If you want a different moving average, you can apply it yourself before charting.

Or follow #318

**Comment by taismi** [comment]
Is there a simple template how to add  a different moving average which can be used with 'plotter: Dygraph.Plotters.linePlotter' and 'plotter: smoothPlotter'?

**Comment by taismi** [comment]
Not incorporating data from the future might be equally important. Yes it might be if you are calculating average electricity price from last 12 months like it is done in some statistics. But this is a special case. If I wanted to check the price in June I would like that the average is calculated from April, May, June, July and August not from February, March, April, May and June. Plotting trailing average against time is not a good idea.
