### ISSUE TITLE
Allow millisecond date ticks

### ISSUE THREAD

**Issue by jtbandes** [danvk/dygraphs#776]
Hi, I just started using dygraphs and it's great! 😄 

I noticed that dygraph-tickers.js seems to [define `DATEFIELD_MS`](https://github.com/danvk/dygraphs/blob/b4b9eeac8b116c18bbf6ebb0c4d542a3f8d2ce32/src/dygraph-tickers.js#L257), but this value is not used in any of the `TICK_PLACEMENT`s. It'd be great if Granularity had some values like `{FIVE,TWO,ONE}_HUNDRED_MILLISECONDLY`, `{FIFTY,TWENTY,TEN}_MILLISECONDLY`, and `{FIVE_,TWO_,}MILLISECONDLY` whose placements could use the milliseconds field.

On a broader note, though, as a client of the library, I wasn't able to do this myself very easily because of how the `dateTicker` is structured — even though `getDateAxis` is exported, the `granularity` passed to it is used to look up a value in the non-exported `TICK_PLACEMENT` array (and `pickDateTickGranularity` is also private). This might be improved by having `getDateAxis` accept the `{datefield, step, spacing}` as arguments, rather than the granularity — then users could replicate+modify the default `dateTicker` more easily. Just a thought 😺

**Comment by jtbandes** [comment]
(I'd be up for implementing this and submitting a PR, but you'll have to let me know which approach you prefer.)

**Comment by pierriko** [comment]
Hi, I had started working on that but din't finish yet, I just opened https://github.com/danvk/dygraphs/pull/777

**Comment by jtbandes** [comment]
Looks like this was done in https://github.com/danvk/dygraphs/pull/893
