### ISSUE TITLE
real time usage or example in React?

### ISSUE THREAD

**Issue by scheung38** [danvk/dygraphs#789]
Does dygraph offer real time examples in React.Component? I have update coming from AWS and I am using MongodB every 30 mins of format:

```
{
  "_id" : ObjectId("57d9209236b7c31958782bd2"),
  "point_id" : "130-E9DCE6-1327/10",
  "time" : "01/08/2015 01:30",
  "offset" : 1,
  "energy" : 29,
  "code" : 0,
  "created_date" : ISODate("2016-09-14T00:00:00Z")
}
{
  "_id" : ObjectId("57d9209236b7c31958782bd3"),
  "point_id" : "130-E9DCE6-1327/10",
  "time" : "01/08/2015 02:00",
  "offset" : 1,
  "energy" : 28,
  "code" : 0,
  "created_date" : ISODate("2016-09-14T00:00:00Z")
}
```

and I like plot time vs energy, at the moment in my server.js I read in data via MongodB 

```
MongoClient = require('mongodb').MongoClient, assert = require('assert');
var url = 'mongodb://ec2-XX-XX-XXX-XX.us-west-2.compute.amazonaws.com:27017/storedata';

MongoClient.connect(url, function (err, db) {
    assert.equal(null, err);
    console.log("Connected successfully to energy server!");

         findDocuments(db, function () {
            db.close();
        });
});

var findDocuments = function (db, callback) {
    var collection = db.collection('energydata');
    console.log('This is collection : ', collection);

    var myCount = db.collection('energydata').count();
    console.log('Counted number of documents : ', myCount);

    // Find some documents
    collection.find({}).toArray(function (err, chartData) {
        assert.equal(err, null);
        console.log("Found the following records");
        console.log(chartData);
        console.log('Type of doc is : ', typeof(chartData)); //Type of doc is :  object
        console.log('Object 0 energy is :', chartData[0].energy); //  16
        console.log('Object 0 time is :', chartData[0].time); //   06/08/2015 10:00
        console.log('Object 0 time is :', chartData[1].time); //  06/08/2015 10:30
        console.log('Object 0 time is :', chartData[2].time); //  06/08/2015 11:00
 
        callback(chartData);
    });
};
```
Not sure how to plot this in dygraph in React and if support for real time?

**Comment by danvk** [comment]
Just call `updateOptions` with a `file` parameter to change the data you're plotting. You can follow http://dygraphs.com/tests/dynamic-update.html as an example.

FWIW I've used dygraphs with React but haven't published any sort of wrapper. But I'd consider bundling that as an add-on. It's very straightforward.

**Comment by scheung38** [comment]
In the dynamic-update.html:

What is the implication of:
  
    // It sucks that these things aren't objects, and we need to store state in window.
      window.intervalId = setInterval(function() {
        var x = new Date();  // current time
        var y = Math.random();
        data.push([x, y]);
        g.updateOptions( { 'file': data } );
      }, 0.1);
    }

Also the Date format: you mentioned updateOptions with file parameter, could you show example?

JSON is not supported yet, correct?


Is it easily convertible into a React Component? Can you provide example of React wrapper that you mentioned?
