### ISSUE TITLE
Gridline Formatter

### ISSUE THREAD

**Issue by pragun16** [danvk/dygraphs#806]
Do we have something like a gridlineformatter like the axisLabelFormatter and valueFormatter? I desperately need to customize the grid lines for an ECG graph.

**Comment by kberg** [comment]
Do you mean http://dygraphs.com/options.html#gridLineColor and http://dygraphs.com/options.html#gridLinePattern ?

**Comment by pragun16** [comment]
No not really. I wanted to generate dynamic gridLineWidth / gridLineColor like in normal graphs. Say 5 small grids give out a larger graph with thicker line width. Also, I'd like to customize the gridlines in the graph to be plotted according to labels on an axis.

**Comment by pragun16** [comment]
I just came across the `ticker` thing. But I'm still facing difficulties in understanding how it really works. It'd be great if somebody explains it to me or provide me with resources for a better understanding.
