### ISSUE TITLE
the x axis and legend are off from one another by 8 hours

### ISSUE THREAD

**Issue by xekon** [danvk/dygraphs#822]
Filing a bug report: the x axis is correct(local time), the legend shows +8 hours

1. http://jsfiddle.net/6v504tLx/
2. database and website live on ubuntu server 16.04.1, client webpage chrome win7 64
3. Version of dygraphs 1.1.1, tried regular and dev

https://s29.postimg.org/5xgesvlxj/help.jpg

any questions, please ask me, would love it if the legend showed the date correctly, so far i love this library, just switched from using google charts, and this is so much quicker.

**Comment by danvk** [comment]
This is a time zone issue. You've set `labelsUTC: true`. If you drop that option, the two will be in sync.

If you'd like to show the axis and legend in a specific time zone (not the user's time zone), you'll need to do the formatting yourself with `axisLabelFormatter` and `valueFormatter`.

**Comment by xekon** [comment]
if you look at my posted jsfidde, I actually set labelsUTC: false, not true. does that make a difference?

however, if i can fix the problem with axislabelformatter and valueformatter that would be great!

**Comment by danvk** [comment]
Ah, sorry, I got it flipped. You have it set to `false`. Setting it to `true` puts the two in sync.

To format times according to a specific time zone and locale, you'll either need to format all the times on the server and send them to the client or use moment-timezone:
http://momentjs.com/timezone/

**Comment by xekon** [comment]
ah before I write a script to modify all the timestamps in my db could you double check or explain something for me, on this example: http://dygraphs.com/tests/labelsDateUTC.html

the labelsUTC option is set, and in both the bottom and top chart the legend and the time correspond, regardless of the labelsUTC setting, but for me this setting only fixes my xaxis and not my legend, do you know the reason for that?

**Comment by danvk** [comment]
http://jsfiddle.net/6v504tLx/1/

works with both values for `labelsUTC`. The difference is passing in date objects & not setting the x-axis options explicitly.

**Comment by xekon** [comment]
AH! you are correct! thank you so very much I appreciate your response, and love the library. that was the last hickup in my project, all thats left is to add a few new features and im done, YAY! thanks again.

**Comment by xekon** [comment]
danvk, thank you for the help thus far. I think I have found a solution but it does not appear to be working.

I have posted the code on stackoverflow, but figured I should ask here as well since you wrote dygraphs you can probably spot what it is that i am doing wrong. http://stackoverflow.com/questions/41540131/how-to-deserialize-json-date-for-dygraph-native-array-format

here is my original method that works except the legend is wrong, test.php:

`
	<?php
		$table[] = [1482407341000,92,86];
		$table[] = [1482407342000,92,86];
		$table[] = [1482407343000,91,85];
		$table[] = [1482407344000,92,85];
		$table[] = [1482407345000,91,84];
		$table[] = [1482407346000,90,83];
		$table[] = [1482407347000,91,82];
		$table[] = [1482407348000,92,82];
		$jsontable = json_encode($table);
		echo $jsontable;
	?>
	<html><head><script type="text/javascript" src="dygraph-combined-dev.js"></script></head>
	<body><div id="graph" style="width:100%; height:96%;"></div>
	<script type="text/javascript">
		g = new Dygraph(document.getElementById("graph"),
		<?=$jsontable?>,
		{
			legend: 'always',
			labelsDivStyles: { 'textAlign': 'right' },
			labels: ['Date', 'spO2', 'pr'],
			axes: {
			x: {
			valueFormatter: Dygraph.dateString_,
			axisLabelFormatter: Dygraph.dateAxisFormatter,
			ticker: Dygraph.dateTicker
			}
			}
		});
	</script></body></html>
`

Now, here is my attempt at a solution, it should work, but dygraphs fails to load, so there must still be a problem with the format of my variable, no error message is displayed so i am unsure why dygraphs does not load,

test2.php:

`
	<?php
		$table[] = ["1482407341000",92,86];
		$table[] = ["1482407342000",92,86];
		$table[] = ["1482407343000",91,85];
		$table[] = ["1482407344000",92,85];
		$table[] = ["1482407345000",91,84];
		$table[] = ["1482407346000",90,83];
		$table[] = ["1482407347000",91,82];
		$table[] = ["1482407348000",92,82];
		$jsontable = json_encode($table);
		echo $jsontable;
	?>
	<html><head><script type="text/javascript" src="dygraph-combined-dev.js"></script>
	<script type="text/javascript">
		function json_deserialize_helper(key,value) {
		if ( typeof value === 'string' ) {
			return new Date(parseInt(value));
		}
			return value;
		}
	</script></head>
	<body><div id="graph" style="width:100%; height:100%;"></div>
	<script type="text/javascript">
		var data = <?=$jsontable?>;
		var json = JSON.parse(data,json_deserialize_helper);
		g = new Dygraph(document.getElementById("graph"),
		json,
		{
			legend: 'always',
			labelsDivStyles: { 'textAlign': 'right' },
			labels: ['Date', 'spO2', 'pr']
		});
	</script></body></html>
`

**Comment by xekon** [comment]
for whatever reason the simplest solution was eluding me. i somehow got caught up on trying to create the date objects, the simplest solution since I was off by 8hours, was just to convert 8hours to millseconds and subtract that from the database results when i retrieve them from my db, and just set labelsUTC: true, so that the two values align.

**Comment by danvk** [comment]
Be careful about time zones. It might not be 8 hours year-round if daylight savings is involved.

**Comment by xekon** [comment]
danvk, I seen in your previous comment that you mention using moment-timezone, http://momentjs.com/timezone/

I like the moment library, I looked for an example on stackoverflow making use of moment with dygraphs:
http://stackoverflow.com/search?q=%5Bdygraphs%5D+moment

the only relevant solution was to basically modify the dygraph script to use moment:
http://stackoverflow.com/questions/24196183/dygraph-showing-dates-in-an-arbitrary-timezone/24196184#24196184

is there a simpler or more elegant solution? or is modifying the dygraph script my best option?
another option would be for me to subtract the 8hours in my php block when i retreive from the databse, but do it in a way that accounts for daylight savings.... but moment js is a javascript app, so I cant use it up there in the php block.
