### ISSUE TITLE
download links not working

### ISSUE THREAD

**Issue by geraldo** [danvk/dygraphs#824]
Download links for dygraph.min.js, dygraph.js and dygraph.css at http://dygraphs.com/download.html are not working. Also hosted version of  of dygraphs 2.0.0 on CDN don't exist.

**Comment by danvk** [comment]
I've fixed the links on the download page.

I've been having some issues sending PRs to cdnjs. I'll close that out once that's finished.

**Comment by danvk** [comment]
The CDN download links are now working.
