### ISSUE TITLE
Add built file to git repo

### ISSUE THREAD

**Issue by maruilian11** [danvk/dygraphs#828]
Hi! I'm from [cdnjs](https://github.com/cdnjs).  We have hosted your lib on https://cdnjs.com. Recently we found out your file structure has changed(2.0.0). Could you please consider providing the built `dist` on git repo like `dygraph-combined.js` in pre-versions before because our auto-update bot can't built the `dist` by itself.

Thank you very much!
https://github.com/cdnjs/cdnjs/issues/10358

**Comment by danvk** [comment]
Thanks @maruilian11. I chimed in on the cdnjs thread — I'd much prefer if cdnjs could pull build artifacts from NPM going forward, rather than from github.
