### ISSUE TITLE
In version 2.0 the legend is stuck to the left of the graph

### ISSUE THREAD

**Issue by yemling** [danvk/dygraphs#831]
See http://jsfiddle.net/2bowy78d/2/
It is positioned correctly in previous releases.

**Comment by pshevtsov** [comment]
@yemling See [release notes for 2.0](https://github.com/danvk/dygraphs/releases/tag/v2.0.0):
> ## Breaking changes
> * There's now a dygraph.css file that you must include.

Adding `dygraph.css` fixes the issue: http://jsfiddle.net/2bowy78d/6/

**Comment by yemling** [comment]
My apologies. Thank you.
