### ISSUE TITLE
Data is displayed incorrectly

### ISSUE THREAD

**Issue by mathisloge** [danvk/dygraphs#834]
The array is constructed as follows:
![image](https://cloud.githubusercontent.com/assets/13556116/22526895/5ce2390c-e8cd-11e6-928a-ac0a6634c9fe.png)

But the Graph shows wrong Data for example (references the data in the upper image)
![image](https://cloud.githubusercontent.com/assets/13556116/22526949/987f80c8-e8cd-11e6-84f2-c681c2fa3af4.png)
Normally it should display 0, 701, 580 :/ 

I use the latest release 2.0

**Comment by danvk** [comment]
did you set a rollPeriod or something? hard to debug without a reproducible example.

**Comment by mathisloge** [comment]
oh embarrassing. If i commented rollPeriod out. it displays the correct values.
