### ISSUE TITLE
Crosshair and Legend throws error if no point is selected

### ISSUE THREAD

**Issue by mathisloge** [danvk/dygraphs#835]
I created the chart dynamicly. But if no point is selected this line: [https://github.com/rstudio/dygraphs/blob/master/inst/plugins/crosshair.js#L58](https://github.com/rstudio/dygraphs/blob/master/inst/plugins/crosshair.js#L58)
throws an error because `e.dygraph.selPoints_` is empty. 
If I surround it with `if(e.dygraph.selPoints_.length > 0 )` :
```
if(e.dygraph.selPoints_.length > 0 ) {
        var canvasx = Math.floor(e.dygraph.selPoints_[0].canvasx) + 0.5; // crisper rendering

        if (this.direction_ === "vertical" || this.direction_ === "both") {
            ctx.moveTo(canvasx, 0);
            ctx.lineTo(canvasx, height);
        }

        if (this.direction_ === "horizontal" || this.direction_ === "both") {
            for (var i = 0; i < e.dygraph.selPoints_.length; i++) {
                var canvasy = Math.floor(e.dygraph.selPoints_[i].canvasy) + 0.5; // crisper rendering
                ctx.moveTo(0, canvasy);
                ctx.lineTo(width, canvasy);
            }
        }
    }
```
It runs without an error 

Also happen at [https://github.com/danvk/dygraphs/blob/master/src/plugins/legend.js#L114](https://github.com/danvk/dygraphs/blob/master/src/plugins/legend.js#L114) `dygraph.js:formatted:10649 Uncaught TypeError: Cannot read property 'x' of undefined`

This are my options 
![image](https://cloud.githubusercontent.com/assets/13556116/22560374/9f4dd100-e974-11e6-942c-9176f0d816a4.png)

I use the Crosshair and the smoothplotter

**Comment by pshevtsov** [comment]
@mathisloge could you please provide a minimal working example of your dynamically created chart? A R/Shiny snippet is fine too.

**Comment by mathisloge** [comment]
closing this since i don't work on the project anymore and don't have a example. Sorry!
