### ISSUE TITLE
Show only date on X-axis

### ISSUE THREAD

**Issue by RadhiFadlillah** [danvk/dygraphs#841]
I have daily data like this :

| Date | Income |
|--------|-----------:|
| 2017-02-01| 150|
| 2017-02-02| 200|
| 2017-02-03| 300|

When I turn data above into chart ([JSFiddle](https://jsfiddle.net/eg74ncdh/)), Dygraph by default will show time between two dates :

![date only](https://cloud.githubusercontent.com/assets/6129042/22781312/8a671b7c-eef4-11e6-8ac7-9f8ba666f490.png)

Is it possible to only show date, and no time, in X-axis ?

**Comment by danvk** [comment]
This is a manifestation of #369. Please thumbs up that issue if you'd like to see it addressed in the future.

I agree that this is a real oddity! As a workaround, you could try increasing `pixelsPerLabel` on the x-axis.
