### ISSUE TITLE
Google Chrome 57.0.2987.133 Memory Leak

### ISSUE THREAD

**Issue by nathan546** [danvk/dygraphs#860]
1. http://jsfiddle.net/fc70y57d/
2. Google Chrome, 57.0.2987.133
3. Occurs in both the latest 2.00 (2017) and a 2014 version.

```html
 $(document).ready(function () {
      var data = [];
      var t = new Date();
      for (var i = 10; i >= 0; i--) {
        var x = new Date(t.getTime() - i * 1000);
        data.push([x, Math.random()]);
      }

      var g = new Dygraph(document.getElementById("div_g"), data,
                          {
                            drawPoints: true,
                            showRoller: true,
                            valueRange: [0.0, 1.2],
                            labels: ['Time', 'Random']
                          });
      // It sucks that these things aren't objects, and we need to store state in window.
      window.intervalId = setInterval(function() {
      
      	for(var i = 0; i < 10; i++){
          var x = new Date();  // current time
          var y = Math.random();
          data.push([x, y]);
          if(data.length > 3000)
            data.shift();
        }

        g.updateOptions( { 'file': data } );
      }, 10);
    }
);
```

Doing a "Timeline" analysis in Chrome's Developer Tools with the "Memory" option checked, over a period of about 50 seconds, shows a continuous upwards trend on the number of nodes and listeners.

![memoryleak](https://cloud.githubusercontent.com/assets/114355/25667796/a3b106f8-2ff2-11e7-832e-d17879f0d348.png)
![chromeversion](https://cloud.githubusercontent.com/assets/114355/25667797/a3b20fda-2ff2-11e7-9e88-3c3da59432bc.png)

If you want to run it outside of JS Fiddle:

[standalone-demo.zip](https://github.com/danvk/dygraphs/files/973808/standalone-demo.zip)

**Comment by littonjg** [comment]
I believe the leak is caused by the registeredEvents_.  Every event listener is added to this array and is never removed until dygraph.destroy is called, thereby holding onto the DOM elements so they cannot be garbage collected.

**Comment by williamjshipman** [comment]
Was this issue ever resolved? I seem to be suffering the same memory leak.

**Comment by mirabilos** [comment]
@nathan546 how does one “do a Timeline analysis”? It looks totally different for me…

![Untitled](https://user-images.githubusercontent.com/861078/214768556-920dfd20-48f8-4c6e-b348-cc548a24b866.png)

I normally use Firefox ESR (currently 102) for GUI/JS things, so…

**Comment by mirabilos** [comment]
I found this, and it doesn’t appear to leak anywhere. (I *did* remove a bad (doubled) `appendChild()` call for 2.2.0…)

![Untitled](https://user-images.githubusercontent.com/861078/214770076-e8482758-8a7b-4408-af45-9a706fe74e0c.png)

**Comment by mirabilos** [comment]
[dy860.zip](https://github.com/danvk/dygraphs/files/10507015/dy860.zip)

I suspect your ancient jQuery version is the issue you’ve been seeing and/or the issues in dygraphs have been fixed since. Please retest, and reopen if you still see noticeable/ever-increasing memory leaks.

Thanks!
