### ISSUE TITLE
demo page broken

### ISSUE THREAD

**Issue by mustmodify** [danvk/dygraphs#861]
Filing a bug report? Please include the following:

1. Link to a page which demonstrates the problem, preferably a jsfiddle
http://dygraphs.com/gallery/

2. Browser and Operating System that exhibit the problem
M$ Windows 10 / Chrome

3. Version of dygraphs that you're using
Whatever you're using

Interesting way to freak out the browser. Any other link is fine. But click on "Custom Interaction Models" ... then try to click on any other link. Does nothing.

**Comment by danvk** [comment]
Can confirm:

```
Uncaught TypeError: Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present.
    at Object.clean (interaction.js:89)
    at HTMLDivElement.<anonymous> (gallery.js:50)
```

The gallery hasn't been updated in ages. The real solution here is to replace it.

**Comment by zemadz** [comment]
I have made a pull request to fix it three and a half months ago: https://github.com/danvk/dygraphs/pull/825

Maybe merge it it to fix it?

**Comment by pshevtsov** [comment]
I see that #825 is merged, so closing this issue.
