### ISSUE TITLE
Y-axis labels aren't being rotated in 2.0.0

### ISSUE THREAD

**Issue by koitsu** [danvk/dygraphs#872]
In dygraphs 2.0.0, Y-axis labels aren't being rotated 270 (-90) degrees.  Digging into it further, the ``transform`` CSS property isn't being used anywhere.  The following manual workaround in CSS can be used:

``
#div_g .dygraph-ylabel { transform: rotate(270deg); }
``

While here: in the dygraphs documentation, the ylabel option mentions something called yAxisLabelWidth, except that isn't mentioned or documented anywhere else and leads me to believe it's not real (changing this option seems to do nothing).  This seems different than yLabelWidth in some way?  It's hard to tell; read the ylabel paragraph and you'll see why it's bizarre/confusing.

Likewise, the docs say "The text will be rotated 90 degrees by default".  Nope -- 90 != 270 (-90).

**Comment by danvk** [comment]
Are you including the dygraphs CSS file on your page?

**Comment by koitsu** [comment]
Ah ha! That was it. I had mistakenly used ``src="/path/to/dygraph.css`` in ``<link>`` (it's ``href``, not ``src``).  I should have reviewed the Network tab in Chrome to see what resources were being loaded.  Thank you!
