### ISSUE TITLE
Large value causes line not to be rendered

### ISSUE THREAD

**Issue by jtbandes** [danvk/dygraphs#886]
https://jsfiddle.net/zwybt1vL/
A very large value will surprisingly prevent other points and line segments in a series from being rendered, even if they should be visible given the valueRange.

```js
var data = [2, 10000000000, 10, 11, 15, 2, 3];

new Dygraph(
  document.getElementById("graph"),
  data.map((d, i) => [i, d]),
  {valueRange: [0, 14]});
```
![bug](https://user-images.githubusercontent.com/14237/31750770-ddccc5ca-b436-11e7-8892-d195b3df5f3f.gif)

Notice that the point is visible on mouseover, but the line is **not** visible. If the value is changed from `10000000000` to `10000000`, the line appears.

Observed with Dygraphs v2.0.0. Bug occurs on macOS Chrome & Safari, and Ubuntu Chrome.

**Comment by danvk** [comment]
that is... surprising

**Comment by danvk** [comment]
Looks like it's a Chrome bug, not a dygraphs bug. https://jsfiddle.net/4rssL7np/
Feel free to follow up with them.

**Comment by jtbandes** [comment]
Unfortunately it also seems to be a Safari bug and a Firefox bug.

Would it make sense for Dygraphs to work around this by limiting the points to some extreme (but slightly less extreme) range?

**Comment by danvk** [comment]
I'd really prefer to avoid working around browser issues, especially in an era of fast browser update cycles. I'll be curious what the Chrome/Safari people have to say about this.
