### ISSUE TITLE
[FEATURE REQUEST] Shared Crosshair Option for Grouped Charts

### ISSUE THREAD

**Issue by ckatsulis** [danvk/dygraphs#894]
The `group` function in `dygraphs` is particularly useful for a series of related plots if you want to x-axis zoom in unison.  I was looking for a feature or parameter that would also allow the mouseover legend values to be synchronized across the grouped dygraphs. I see some functionality in the package relating to mouseover, however nothing with x or y coordinates in R.

This would be for use in a shinyapp.  Grafana has a similar option/feature where all of the crosshair is shared across linked charts:

![image](https://user-images.githubusercontent.com/7516330/33776478-1dfd21b0-dc07-11e7-84d0-592fa98bdd7c.png)

https://stackoverflow.com/questions/44918005/sync-legend-values-across-grouped-dygraphs

**Comment by pshevtsov** [comment]
@ckatsulis it's better to submit such feature request to the rstudio/dygraphs repo, but I remember that similar issues were already submitted there.
