### ISSUE TITLE
possible to change output on hover

### ISSUE THREAD

**Issue by sachinbanugariya** [danvk/dygraphs#951]
hello,

i used dygraphs, good library,
but seems like there is not much better way to view data for user at corner with arrow drag on line chart,
is it possible to make hover based output with axis move, not one arrow move?
also attached screenshot of sample chart.
thanks
![untitled](https://user-images.githubusercontent.com/22053179/49377610-a693e000-f730-11e8-80ba-de70b15b1b69.png)

**Comment by mirabilos** [comment]
I fear I totally do not understand what you’re asking here.

Since it’s been over 4 years, I’m closing for now, but please do reopen if you’re still interested.
