### ISSUE TITLE
unexpected behavior of clickCallback with highlightSeriesOpts

### ISSUE THREAD

**Issue by yairtal** [danvk/dygraphs#954]
Use highlightSeriesOpts along with clickCallback

expected:
clickCallback will return the x of the click's location on the graph

result:
clickCallback returns the x of the closet point on the closest graph

**Comment by mirabilos** [comment]
Hmm, this is documented, though. And you get the original event, which contains the click coordinates. Is that somehow not enough?

It’s been 4 years, so I’m closing this, but feel free to reopen if you’re still interested.
