### ISSUE TITLE
duplicate series labels only show value for last series

### ISSUE THREAD

**Issue by michaud** [danvk/dygraphs#960]
https://github.com/danvk/dygraphs/blob/da2a028fc41e5573868358b3d9eda9826211d217/src/dygraph-options.js#L146
https://github.com/danvk/dygraphs/blob/da2a028fc41e5573868358b3d9eda9826211d217/src/dygraph-options.js#L150

when using the label as a series identifier the data gets overwritten if the label appears multiple times in this.labels_
using the labels as a dictionary field in this case creates a weakness, who knows what people put in those labels

**Comment by mirabilos** [comment]
Yes, you cannot use duplicate labels. What they put there is converted to a String, since that’s what dictionary keys are; otherwise, the GIGO principle applies here.
