### ISSUE TITLE
dygraphs, update data in native JS format

### ISSUE THREAD

**Issue by Saturnix** [danvk/dygraphs#969]
I'm aware there is a way to update data of a dygraphs graph by providing a new data file.

```javascript
g.updateOptions( { 'file': new_data } );
```
However, I'm using dygraphs not with files but with JavaScript arrays

```javascript
this.aggregatedGraph = new Dygraph(
    // containing div
    document.getElementById("aggregatedgraph"),
    [[0, 0], [1, 1], [2, 4]],

    {
        labels: ["foo", "bar"],
    }
);
```

How can I update the data without having to `.empty()` the div and redraw the whole chart (thus loosing all the user zoom/panning)?

I've tried these:
```javascript

// gives error, "data option does not exists"
this.aggregatedGraph.updateOptions({
    data: [[0, 0], [1, 1], [2, 4], [3, 14]]
})

// shows nothing
this.aggregatedGraph.updateOptions({
    file: [[0, 0], [1, 1], [2, 4], [3, 14]]
})
```

**Comment by mirabilos** [comment]
The latter should actually work; it is used in *many* places in the samples and tests.

If you find a situation in which it doesn’t work, please provide a reproducer.
