### ISSUE TITLE
gridLineColor different on axis

### ISSUE THREAD

**Issue by vinnitu** [danvk/dygraphs#974]
Hi!

![image](https://user-images.githubusercontent.com/432168/66298976-4eeb7580-e8fb-11e9-8e0c-4312299e73b3.png)
 
As I see one axis is red, other light red.
How to do same color for both?

**Comment by mirabilos** [comment]
That’s an antialiasing artefact, caused by your physical pixel size being just slightly larger than the stroke width of the grid. Adjust the latter.
