### ISSUE TITLE
Wrong package version of the package on npm

### ISSUE THREAD

**Issue by coderi-sk** [danvk/dygraphs#983]
When you install the package
``` 
npm install dygraphs@2.1.0
```
it seems to install the right version, but in reality it installs the 2.0.0 version of the package.
Proof:
```
import Dygraph from 'dygraphs';
console.log(Dygraph.VERSION);
```
prints:
```
2.0.0
```

**Comment by mirabilos** [comment]
Should be fixed for `2.1.2` although, looking at it, I just think the NPM package was built with the wrong version number baked in, as the other changes in 2.1.0 are present.
