### ISSUE TITLE
Improper data type detection (Couldn't parse 20033000 as a date)

### ISSUE THREAD

**Issue by lmizinski** [danvk/dygraphs#984]
Dygraphs version:
2.1.0

JsFiddle showing error:
https://jsfiddle.net/2pcu7swo/2/

I discovered the nature of problem. Data with X values like the one in example are treated as date values, and then are parsed as date which results in error:
"Couldn't parse 20033000 as a date"
 
The main problem here is that 20033000 should never be treated as date by default. It greatly limits library. Date can always be passed in regular data format, like  2003-30-00 if necessary. Or there could be flag added, that would force library to treat value as date. 

I will provide pull request with solution for this problem.

**Comment by kraliq233** [comment]
****

**Comment by mirabilos** [comment]
should be fixed in 2.1.2+
