### ISSUE TITLE
Patch: have synchronise handle crosshairs plugin too

### ISSUE THREAD

**Issue by sdaau** [danvk/dygraphs#987]
Just wanted to do a quick post here; I've had two graphs (similar to the examples in it https://stackoverflow.com/q/60831822) placed one below another, and wanted a vertical cursor spanning both plots.

It seems I came up with a hack for `synchronizer.js` that does that, it's in respect to http://dygraphs.com/2.1.0/extras/synchronizer.js :

```
--- a/synchronizer.js
+++ b/synchronizer.js
@@ -219,6 +219,15 @@ function attachSelectionHandlers(gs, prevCallbacks) {
           if (idx !== null) {
             gs[i].setSelection(idx, seriesName);
           }
+          // check for crosshairs plugin, synchronize if there
+          var crosshair_plugin_array = gs[i].plugins_.filter(function(e) { return e.plugin.toString() ==  'Crosshair Plugin'; });
+          if (crosshair_plugin_array.length > 0) {
+            var cloneev = Object.assign({}, event);
+            cloneev.dygraph = gs[i];
+            cloneev.dygraph.selPoints_ = me.selPoints_;
+            var crosshair_plugin = crosshair_plugin_array[0];
+            crosshair_plugin.plugin.select(cloneev);
+          }
         }
         block = false;
       },
```

This also handles the case - considering a numeric x-axis - if you hover datapoint on plot 1 with say x=1234, you will get a vertical cursor also on plot2 on the same position, even if data set for plot 2 does not contain a point with x=1234.

Probably there is a better way to do this, but just wanted to document this while I remember.

**Comment by mirabilos** [comment]
Is this still pertinent?

I added `var sync = Dygraph.synchronize(gv, gh, gb);` near the bottom of `tests/crosshair.html` and found them all synchronised.

Please reopen if you still find anything missing here.
