### ISSUE TITLE
Artifacts in stacked area graphs

### ISSUE THREAD

**Issue by qwjhvbxi** [danvk/dygraphs#988]
Hello, I am noticing artifacts when using stacked graph option. An example is shown in this image:

<img width="685" alt="dygraph_problem" src="https://user-images.githubusercontent.com/26291277/78111158-376af080-7437-11ea-8e85-da8c2e8f544c.PNG">

You can check the error at http://riccardoiacobucci.com/rensandbox and zooming in on 25 October.
The error is present both in Chrome and Firefox (latest version).
I am using Dygraphs version 2.1.0.

The errors always appear in the same date, regardless of the data. I could not find anything strange in the data itself.

**Comment by danvk** [comment]
This must be something to do with daylight savings time. You might want to try passing in dates in a more UTC-like format to reduce ambiguity (YYYY-MM-DD instead of YYYY/MM/DD). See [this post][1] for background.

[1]: http://blog.dygraphs.com/2012/03/javascript-and-dates-what-mess.html

**Comment by qwjhvbxi** [comment]
Thank you! It was indeed a problem with daylight saving time! The date format is correct, but because of the change of time there is one hour that is repeated. I will try to look into possible fixes, but in any case it's not a problem with dygraphs. Thanks again!
