### ISSUE TITLE
Trouble importing Synchronise

### ISSUE THREAD

**Issue by evlquaker** [danvk/dygraphs#989]
Hi,

I am pretty new to JavaScript and Node.js. I am trying to use Synchronize with Dygraphs in order to sync multiple graphs with selection and zooming. It seems Synchronize is not imported automatically with Dygraphs. How would I import Synchronize and use it? Help would be much appreciated.

~Mike

**Comment by mirabilos** [comment]
Please see #848; for the synchronise extra, this actually should already work.
