### ISSUE TITLE
x/y scale numbers format

### ISSUE THREAD

**Issue by GoSim-GoSim** [danvk/dygraphs#995]
Version 2.1.0.
Xubuntu 16.04
Firefox 75.0 (64bit)

Look at the x/y scales in the pictures and you will see the errors. The numbers are formatted wrong.

Nice software in general, I hope you fix this. Regards.

![dygraph_x_axis_bug](https://user-images.githubusercontent.com/50754144/80316118-38a3f900-87fc-11ea-9854-6dc669ea2911.png)
![dygraph_y_axis_bug](https://user-images.githubusercontent.com/50754144/80316120-393c8f80-87fc-11ea-8523-7f8cba8c3eec.png)

**Comment by mirabilos** [comment]
Please provide the test files (HTML/JS and CSV) so we can see what causes this to happen (it does not, normally).

**Comment by mirabilos** [comment]
I think you just have to specify appropriate `digitsAfterDecimal` or possibly a `valueFormatter` to match your data.
