### ISSUE TITLE
Plotting nanoseconds on the x-axis

### ISSUE THREAD

**Issue by psaigal95** [danvk/dygraphs#996]
I have a csv which has around a million points of the type:
2020-02-13 03:30:01.966207567,68
2020-02-13 03:30:01.979959429,68
2020-02-13 03:30:02.001963884,68
2020-02-13 03:30:02.002054163,68
2020-02-13 03:30:02.006274936,68
2020-02-13 03:30:02.021821085,68

Is there a way in Dygraph to plot the x-axis with nanoseconds precision.
Pardon me if I am missing something obvious.

**Comment by psaigal95** [comment]
@danvk

**Comment by mirabilos** [comment]
JavaScript’s Date doesn’t do more than milliseconds.

I have the same problem and am solving it by using a numeric base starting at 0 (in your example, the first data point would be `0.966207567`) and document what offset 0 corresponds to outside the plot.

**Comment by mirabilos** [comment]
unfortunately out of scope, but I hope I gave a helpful workaround
