### ISSUE TITLE
please put up a lack of maintenance notice

### ISSUE THREAD

**Issue by leeoniya** [danvk/dygraphs#999]
@danvk @lmizinski

dygraphs is effectively an abandoned project, which is perfectly okay.

however, it would be helpful to update the README making this clear to prevent people from continuing to submit new issues and wasting time working on PRs that will never be reviewed, let alone merged.

if you guys are feeling generous (and as a token of appreciation for me wasting a bunch of time to get all tests passing in https://github.com/danvk/dygraphs/pull/948#issuecomment-451754817), i would appreciate a link to https://github.com/leeoniya/uPlot and perhaps some other actively-maintained alternatives [1].

i really don't want to spam all the ignored issues here which are dealing with never-to-be-addressed dygraphs features or bugs that have been long-solved (or at least have a chance of getting addressed) in uPlot.

either way, thanks for dygraphs. it has served me well in the past and was a major UI inspiration for uPlot.

cheers!

[1] https://github.com/leeoniya/uPlot#performance

**Comment by danvk** [comment]
Hi @leeoniya, that's a reasonable request. I can put up a notice explaining what to expect and what not to expect in terms of dygraphs maintenance. I can also mention alternative libraries, including yours.

I'd appreciate it if you stop the passive aggressive comments about that PR in your communications with and about me. I apologized for not merging it. I offered to add you as a maintainer. It's been 18 months. I think it's time to let it go. Can you do that?

Best of luck with uPlot.

**Comment by leeoniya** [comment]
> I can put up a notice explaining what to expect and what not to expect in terms of dygraphs maintenance.

thank you.

> I'd appreciate it if you stop the passive aggressive comments about that PR in your communications with and about me. I apologized for not merging it. I offered to add you as a maintainer. It's been 18 months. I think it's time to let it go. Can you do that?

i will happily do that. the only reason i keep doing it is because for 18 months i'm seeing people who, like me, try to contribute and get radio silence. had it been made obvious in a prominent README banner that the project is not being maintained & is seeking maintainers, i would probably still have made the Rollup PR, but certainly not have spent the additional time to getting the tests passing (since the Rollup conversion was both low effort and worked just fine for my use-cases).

anyways, i have no personal grudge against you or my specific PR - just that it should have been a signal to respect others' time in the future, and that opportunity has languished for 18 months perhaps because some buried "looking for maintainers" issue was still open (it's not even pinned).

i would actually prefer that you not make specific endorsements for uPlot as simply a favor but purely on its merits if you feel it's a worthy spiritual successor. additionally or alternatively, if you don't want to maintain a list of other libs, you can simply link to https://github.com/leeoniya/uPlot#performance, which will passively vouch for it anyhow.

thanks!
